import test from 'node:test';
import assert from 'node:assert/strict';
import {PassThrough,Writable} from 'node:stream';
import {CodexRpc} from '../src/codex-rpc.js';
function fixture(t:test.TestContext,options:ConstructorParameters<typeof CodexRpc>[2]={}){const input=new PassThrough(),output=new PassThrough();const sent:unknown[]=[];output.on('data',b=>sent.push(JSON.parse(String(b))));const rpc=new CodexRpc(input,output,options);t.after(()=>rpc.close());return {input,output,sent,rpc};}
test('fragmented UTF8 and adjacent notification/response lines resolve only matching id',async t=>{const seen:unknown[]=[],f=fixture(t,{onNotification:m=>seen.push(m)}),pending=f.rpc.call('thread/read',{threadId:'owned'});const id=(f.sent[0] as {id:number}).id,bytes=Buffer.from(JSON.stringify({method:'thread/status/changed',params:{text:'한글'}})+'\n'+JSON.stringify({id,result:{thread:{id:'owned'}}})+'\n');for(let i=0;i<bytes.length;i++)f.input.write(bytes.subarray(i,i+1));assert.deepEqual(await pending,{thread:{id:'owned'}});assert.equal(seen.length,1);});
test('timeout does not resubmit and late response cannot resolve a new request',async t=>{const f=fixture(t,{timeoutMs:10});await assert.rejects(f.rpc.call('turn/start',{}),/rpc_timeout/);const old=(f.sent[0] as {id:number}).id,second=f.rpc.call('thread/read',{}),id=(f.sent[1] as {id:number}).id;f.input.write(JSON.stringify({id:old,result:'late'})+'\n'+JSON.stringify({id,result:'current'})+'\n');assert.equal(await second,'current');assert.equal(f.sent.length,2);});
test('EOF rejects in-flight requests and refuses subsequent calls',async t=>{const f=fixture(t),pending=f.rpc.call('thread/read',{});f.input.end();await assert.rejects(pending,/rpc_closed/);await assert.rejects(f.rpc.call('thread/read',{}),/rpc_closed/);});
test('malformed or oversized peer data rejects all requests without exposing raw contents',async t=>{for(const payload of ['PRIVATE_CREDENTIAL_TEXT\n','x'.repeat(100)]){const f=fixture(t,{maxLineBytes:64}),pending=f.rpc.call('thread/read',{});f.input.write(payload);await assert.rejects(pending,/rpc_protocol_error|rpc_frame_too_large/);await assert.rejects(f.rpc.call('thread/read',{}),/rpc_closed/);}});
test('server approval requests are denied by default and cannot act as responses',async t=>{const f=fixture(t),pending=f.rpc.call('thread/read',{}),id=(f.sent[0] as {id:number}).id;f.input.write(JSON.stringify({id,method:'item/commandExecution/requestApproval',params:{command:'PRIVATE_COMMAND'}})+'\n');assert.equal((f.sent[1] as {error:{code:number}}).error.code,-32601);f.input.write(JSON.stringify({id,result:{ok:true}})+'\n');assert.deepEqual(await pending,{ok:true});});
test('remote errors expose only numeric code and never credential-bearing messages',async t=>{const f=fixture(t),pending=f.rpc.call('thread/read',{}),id=(f.sent[0] as {id:number}).id;f.input.write(JSON.stringify({id,error:{code:-32600,message:'PRIVATE_CREDENTIAL_TEXT'}})+'\n');await assert.rejects(pending,/rpc_remote_error:-32600/);});
test('output write failure fences the connection before any later request',async t=>{const input=new PassThrough(),output=new Writable({write(_chunk,_encoding,callback){callback(new Error('SECRET_WRITE_FAILURE'));}}),rpc=new CodexRpc(input,output);t.after(()=>rpc.close());await assert.rejects(rpc.call('turn/start',{}),/rpc_write_failed|rpc_backpressure|rpc_closed/);await assert.rejects(rpc.call('thread/read',{}),/rpc_closed/);});
test('bounded pending calls and outbound frames refuse work without writing',async t=>{const f=fixture(t,{maxPending:1,maxLineBytes:128}),first=f.rpc.call('thread/read',{});await assert.rejects(f.rpc.call('turn/start',{}),/rpc_pending_limit/);f.rpc.close();await assert.rejects(first,/rpc_closed/);const g=fixture(t,{maxLineBytes:128});await assert.rejects(g.rpc.call('turn/start',{text:'x'.repeat(256)}),/rpc_frame_too_large/);assert.equal(g.sent.length,0);});
test('stalled output fences repeated host requests before queue growth',t=>{const input=new PassThrough(),output=new Writable({highWaterMark:128,write(){}}),rpc=new CodexRpc(input,output,{maxLineBytes:128,maxPending:1});t.after(()=>rpc.close());input.write('{"id":1,"method":"approval"}\n'.repeat(10000));assert.ok(output.writableLength<=256);});
test('consumed batches release the original backing allocation',t=>{const f=fixture(t,{maxLineBytes:64});f.input.write('{"method":"n"}\n'.repeat(100000));const buffer=(f.rpc as unknown as {buffer:Buffer}).buffer;assert.equal(buffer.length,0);assert.ok(buffer.buffer.byteLength<=64);});
test('closed transports do not accumulate capturing listeners on reused streams',()=>{const input=new PassThrough(),output=new PassThrough();for(let i=0;i<10;i++)new CodexRpc(input,output).close();for(const stream of [input,output]){assert.equal(stream.listenerCount('data'),0);assert.equal(stream.listenerCount('close'),0);assert.ok(stream.listenerCount('error')<=1);}});
