import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../src/store.js';
import {ExecutionController,createMockDriver} from '../src/execution-driver.js';
async function fixture(t:test.TestContext){const dir=mkdtempSync(join(tmpdir(),'durebak-continuation-'));let now=100000;const clock={now:()=>now},store=new Store(dir,clock),db=new DatabaseSync(join(dir,'runtime.sqlite'));db.exec('PRAGMA foreign_keys=ON');t.after(()=>{db.close();store.close();rmSync(dir,{recursive:true,force:true});});const a=store.register('w','a','codex').session,b=store.register('w','b','codex').session,c=store.register('w','c','codex').session;function worker(sessionId:string,nativeId:string,peers:string[]){const binding=store.managedBind({sessionId,harness:'codex',profile:'isolated',nativeId,instance:'owner-'+nativeId,key:'bind-'+nativeId});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,allowedPeers:peers,key:'on-'+nativeId});const driver=createMockDriver({bindingId:binding.binding.id,epoch:1,instance:binding.binding.instance,profile:'isolated',nativeId}),controller=new ExecutionController(db,clock,driver);return {driver,controller,owner:{bindingId:binding.binding.id,epoch:1,instance:binding.binding.instance,ownerToken:binding.ownerToken!,driver:'read-only-mock'}};}
 const B=worker(b.id,'B',[c.id]),C=worker(c.id,'C',[b.id]),root=store.requestCreate(a,{to:b.id,body:'PRIVATE_PARENT_SOURCE',key:'root',priority:'urgent',urgentReason:'test'}),op={...B.owner,messageId:root.message_id,key:'root'},attempt=B.controller.reserve(op);await B.controller.execute({...op,attemptId:attempt.id});store.requestTransition(b,root.id,1,'accepted');return {dir,clock,store,db,a,b,c,B,C,root,parent:{...op,attemptId:attempt.id},advance:(ms:number)=>now+=ms};}
async function reply(f:Awaited<ReturnType<typeof fixture>>){const child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'review only this child source',task:{title:'review',criteria:'exact child result'},key:'child',priority:'urgent',urgentReason:'test'});f.B.driver.setAwaiting(f.parent.attemptId,child.id);await f.B.controller.reconcile(f.parent);const op={...f.C.owner,messageId:child.message_id,key:'child'},attempt=f.C.controller.reserve(op);await f.C.controller.execute({...op,attemptId:attempt.id});f.store.requestTransition(f.c,child.id,1,'accepted',{expectedTaskVersion:1});const artifact=f.store.putArtifact(f.c,'EXACT_CHILD_RESULT'),result=f.store.requestMessage(f.c,{id:child.id,version:2,kind:'result',body:'review result',hash:artifact.hash,expectedTaskVersion:2,key:'result'});f.C.driver.setOutcome(attempt.id,'succeeded');await f.C.controller.reconcile({...op,attemptId:attempt.id});f.advance(5000);return {child,result};}
test('owned child and once-only reply resume the same binding with inherited budget and complete source',async t=>{const f=await fixture(t),{child,result}=await reply(f),op={...f.B.owner,messageId:result.id,key:'continue'},attempt=f.B.controller.reserve(op);assert.equal((await f.B.controller.execute({...op,attemptId:attempt.id})).state,'running');assert.equal(f.B.driver.calls.submit,2);assert.equal(f.B.driver.binding.nativeId,'B');assert.equal(f.db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(f.B.owner.bindingId)!.spent_turns,3);assert.equal(f.db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(f.C.owner.bindingId)!.spent_turns,1);const source=f.db.prepare('SELECT source FROM work_attempts WHERE id=?').get(attempt.id)!.source as string;assert.ok(source.includes('EXACT_CHILD_RESULT'));assert.ok(!source.includes('PRIVATE_PARENT_SOURCE'));assert.equal(f.store.requestGet(f.b,child.id).state,'completed');assert.throws(()=>f.B.controller.reserve({...op,key:'again'}),/continuation_consumed|trigger_unavailable|host_busy/);});
test('child creation is atomic with provenance and cannot adopt an ordinary peer request',async t=>{const f=await fixture(t);f.db.exec("CREATE TRIGGER reject_lineage BEFORE INSERT ON work_children BEGIN SELECT RAISE(ABORT,'injected_lineage_failure'); END");assert.throws(()=>f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'}),/injected_lineage_failure/);assert.equal(f.db.prepare('SELECT count(*) n FROM requests').get()!.n,1);f.db.exec('DROP TRIGGER reject_lineage');const ordinary=f.store.requestCreate(f.b,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});assert.throws(()=>f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'}),/execution_origin_conflict/);assert.equal(f.store.requestGet(f.b,ordinary.id).state,'pending');});
test('root grant exhaustion stops descendants and policy off prevents a waiting continuation',async t=>{const f=await fixture(t),child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});f.db.prepare('UPDATE managed_policies SET spent_turns=30 WHERE binding_id=?').run(f.B.owner.bindingId);assert.throws(()=>f.C.controller.reserve({...f.C.owner,messageId:child.message_id,key:'child'}),/turn_budget_exhausted/);assert.equal(f.C.driver.calls.submit,0);});
test('child targets require explicit user permission and cannot outlive the parent deadline',async t=>{const f=await fixture(t);assert.throws(()=>f.B.controller.createChild(f.parent,{to:f.a.id,body:'not allowed',key:'bad',priority:'urgent',urgentReason:'test'}),/peer_not_allowed/);const child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',deadlineMs:3600000,priority:'urgent',urgentReason:'test'});assert.equal(child.deadline_at,f.root.deadline_at);f.advance(5000);assert.equal(f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',deadlineMs:3600000,priority:'urgent',urgentReason:'test'}).id,child.id);});
test('waiter expiry and cancellation persist without enabling reply history after restart',async t=>{const f=await fixture(t),{child,result}=await reply(f);f.store.managedPolicy({bindingId:f.B.owner.bindingId,version:2,enabled:false,key:'off'});assert.throws(()=>f.B.controller.reserve({...f.B.owner,messageId:result.id,key:'continue'}),/policy_off|continuation_policy_changed/);assert.equal(f.B.driver.calls.submit,1);assert.equal(f.store.requestGet(f.b,child.id).state,'completed');});
test('driver waiting declaration must refer to the exact child execution origin',async t=>{const f=await fixture(t),other=f.store.requestCreate(f.b,{to:f.c.id,body:'ordinary',key:'ordinary',priority:'urgent',urgentReason:'test'});f.B.driver.setAwaiting(f.parent.attemptId,other.id);const result=await f.B.controller.reconcile(f.parent);assert.equal(result.state,'unknown');assert.equal(f.db.prepare('SELECT count(*) n FROM work_waiters').get()!.n,0);});
test('root cancellation stops an accepted descendant and releases both charged grants once',async t=>{const f=await fixture(t),child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});f.B.driver.setAwaiting(f.parent.attemptId,child.id);await f.B.controller.reconcile(f.parent);const op={...f.C.owner,messageId:child.message_id,key:'child'},attempt=f.C.controller.reserve(op);await f.C.controller.execute({...op,attemptId:attempt.id});f.store.requestTransition(f.a,f.root.id,2,'cancelled');assert.equal((await f.C.controller.reconcile({...op,attemptId:attempt.id})).state,'stopped');assert.equal(f.C.driver.calls.interrupt,1);await f.C.controller.reconcile({...op,attemptId:attempt.id});for(const id of [f.B.owner.bindingId,f.C.owner.bindingId])assert.equal(f.db.prepare('SELECT active_turns FROM managed_policies WHERE binding_id=?').get(id)!.active_turns,0);});
test('unknown continuation holds its claim and shared budget without a second submit',async t=>{const f=await fixture(t),{child,result}=await reply(f),op={...f.B.owner,messageId:result.id,key:'continue'},attempt=f.B.controller.reserve(op);f.B.driver.setSubmitMode('lose-response');assert.equal((await f.B.controller.execute({...op,attemptId:attempt.id})).state,'unknown');assert.equal(f.db.prepare('SELECT status FROM work_waiters WHERE request_id=?').get(child.id)!.status,'claimed');assert.equal((await f.B.controller.reconcile({...op,attemptId:attempt.id})).state,'running');assert.equal(f.B.driver.calls.submit,2);});
test('an expired waiter remains expired after clock rollback',async t=>{const f=await fixture(t),{child,result}=await reply(f);f.db.prepare('UPDATE work_waiters SET deadline_at=? WHERE request_id=?').run(f.clock.now(),child.id);assert.throws(()=>f.B.controller.reserve({...f.B.owner,messageId:result.id,key:'continue'}),/continuation_consumed/);f.advance(-1);assert.equal(f.db.prepare('SELECT status FROM work_waiters WHERE request_id=?').get(child.id)!.status,'expired');assert.throws(()=>f.B.controller.reserve({...f.B.owner,messageId:result.id,key:'continue'}),/execution_unknown|continuation_consumed/);});
test('withdrawing root peer permission interrupts the running descendant',async t=>{const f=await fixture(t),child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});f.B.driver.setAwaiting(f.parent.attemptId,child.id);await f.B.controller.reconcile(f.parent);const op={...f.C.owner,messageId:child.message_id,key:'child'},attempt=f.C.controller.reserve(op);await f.C.controller.execute({...op,attemptId:attempt.id});f.store.managedPolicy({bindingId:f.B.owner.bindingId,version:2,enabled:true,allowedPeers:[],key:'withdraw'});assert.equal((await f.C.controller.reconcile({...op,attemptId:attempt.id})).state,'stopped');assert.equal(f.C.driver.calls.interrupt,1);});
test('root pause before submission prevents any descendant driver call',async t=>{const f=await fixture(t),child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});f.B.driver.setAwaiting(f.parent.attemptId,child.id);await f.B.controller.reconcile(f.parent);const op={...f.C.owner,messageId:child.message_id,key:'child'},attempt=f.C.controller.reserve(op);f.store.setSessionState(f.b,'paused');await assert.rejects(()=>f.C.controller.execute({...op,attemptId:attempt.id}),/recipient_paused/);assert.equal(f.C.driver.calls.submit,0);assert.throws(()=>f.C.controller.reserve({...op,key:'different'}),/recipient_paused|trigger_reserved/);});

test('cancelling intermediate parent must stop grandchild',async t=>{
const f=await fixture(t),child=f.B.controller.createChild(f.parent,{to:f.c.id,body:'child',key:'child',priority:'urgent',urgentReason:'test'});
f.B.driver.setAwaiting(f.parent.attemptId,child.id);await f.B.controller.reconcile(f.parent);
const op={...f.C.owner,messageId:child.message_id,key:'child'},attempt=f.C.controller.reserve(op);await f.C.controller.execute({...op,attemptId:attempt.id});f.store.requestTransition(f.c,child.id,1,'accepted');
const grand=f.C.controller.createChild({...op,attemptId:attempt.id},{to:f.b.id,body:'grandchild',key:'grandchild',priority:'urgent',urgentReason:'test'});
f.C.driver.setAwaiting(attempt.id,grand.id);await f.C.controller.reconcile({...op,attemptId:attempt.id});
const grandOp={...f.B.owner,messageId:grand.message_id,key:'grandchild'},grandAttempt=f.B.controller.reserve(grandOp);await f.B.controller.execute({...grandOp,attemptId:grandAttempt.id});
f.store.requestTransition(f.b,child.id,2,'cancelled');
assert.equal((await f.B.controller.reconcile({...grandOp,attemptId:grandAttempt.id})).state,'stopped');
});
