import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {Store} from '../src/store.js';
import {ExecutionController,createMockDriver} from '../src/execution-driver.js';
function fixture(t:test.TestContext){const dir=mkdtempSync(join(tmpdir(),'durebak-driver-'));let now=100000;const clock={now:()=>now},store=new Store(dir,clock),db=new DatabaseSync(join(dir,'runtime.sqlite'));db.exec('PRAGMA foreign_keys=ON');t.after(()=>{db.close();store.close();rmSync(dir,{recursive:true,force:true});});const a=store.register('w','a','codex').session,b=store.register('w','b','codex').session,binding=store.managedBind({sessionId:b.id,harness:'codex',profile:'isolated',nativeId:'owned-thread',instance:'mock-owner',key:'binding'});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'on'});const q=store.requestCreate(a,{to:b.id,body:'exact input',key:'q',priority:'urgent',urgentReason:'test',task:{title:'review',criteria:'exact evidence'}}),input={bindingId:binding.binding.id,epoch:1,instance:'mock-owner',ownerToken:binding.ownerToken!,messageId:q.message_id,key:'intent',driver:'read-only-mock'},driver=createMockDriver({bindingId:binding.binding.id,epoch:1,instance:'mock-owner',profile:'isolated',nativeId:'owned-thread'}),controller=new ExecutionController(db,clock,driver);return {dir,clock,store,db,a,b,q,input,driver,controller,advance:(ms:number)=>now+=ms};}
function budget(db:DatabaseSync,bindingId:string){return db.prepare('SELECT spent_turns,active_turns FROM managed_policies WHERE binding_id=?').get(bindingId)!;}
test('mock acceptance records delivery only; terminal turn is not request completion or verification',async t=>{
 const {store,db,b,q,input,driver,controller}=fixture(t),attempt=controller.reserve(input);assert.equal(db.prepare('SELECT delivered_at FROM messages WHERE id=?').get(q.message_id)!.delivered_at,null);const running=await controller.execute({...input,attemptId:attempt.id});assert.equal(running.state,'running');assert.equal(running.input_accepted,true);assert.equal(running.native_verified,false);assert.equal(running.model_started,false);assert.equal(db.prepare('SELECT status FROM messages WHERE id=?').get(q.message_id)!.status,'delivered');assert.equal(store.requestGet(b,q.id).state,'pending');assert.equal(store.receive(b).items.length,0);driver.setOutcome(attempt.id,'succeeded');const done=await controller.reconcile({...input,attemptId:attempt.id});assert.equal(done.state,'succeeded');assert.equal(budget(db,input.bindingId).active_turns,0);assert.equal(budget(db,input.bindingId).spent_turns,1);assert.equal(store.requestGet(b,q.id).state,'pending');assert.equal(store.requestVerification(b,q.id).status,'unverified');assert.equal(driver.calls.submit,1);
});
test('response loss is quarantined and reconnection observes the same attempt without resubmitting',async t=>{
 const {dir,clock,store,db,b,input,driver,controller}=fixture(t);driver.setSubmitMode('lose-response');const attempt=controller.reserve(input),unknown=await controller.execute({...input,attemptId:attempt.id});assert.equal(unknown.state,'unknown');assert.equal(budget(db,input.bindingId).active_turns,1);assert.equal(store.receive(b).items.length,0);const reopened=new DatabaseSync(join(dir,'runtime.sqlite'));try{const reconnected=new ExecutionController(reopened,clock,driver),running=await reconnected.reconcile({...input,attemptId:attempt.id});assert.equal(running.state,'running');await assert.rejects(()=>reconnected.execute({...input,attemptId:attempt.id}),/submission_uncertain/);}finally{reopened.close();}assert.equal(driver.calls.submit,1);
});
test('durable submission failure calls driver zero times',async t=>{
 const {db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);db.exec("CREATE TRIGGER fail_submit BEFORE UPDATE OF state ON work_attempts BEGIN SELECT RAISE(ABORT,'injected_submit_failure'); END");await assert.rejects(()=>controller.execute({...input,attemptId:attempt.id}),/injected_submit_failure/);assert.equal(driver.calls.submit,0);assert.equal(db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');
});
test('post-submit persistence failure leaves durable fence and permits observation recovery',async t=>{
 const {db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);db.exec("CREATE TRIGGER fail_outcome BEFORE UPDATE OF driver_outcome ON work_attempts BEGIN SELECT RAISE(ABORT,'injected_outcome_failure'); END");const unknown=await controller.execute({...input,attemptId:attempt.id});assert.equal(unknown.state,'unknown');assert.equal(unknown.reason,'outcome_not_recorded');assert.equal(driver.calls.submit,1);assert.equal(db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'submitting');assert.equal(budget(db,input.bindingId).active_turns,1);db.exec('DROP TRIGGER fail_outcome');assert.equal((await controller.reconcile({...input,attemptId:attempt.id})).state,'running');assert.equal(driver.calls.submit,1);
});
test('confirmed nonacceptance refunds charged turn and unlocks cooperative delivery exactly once',async t=>{
 const {store,db,b,input,driver,controller}=fixture(t);driver.setSubmitMode('reject');const attempt=controller.reserve(input),result=await controller.execute({...input,attemptId:attempt.id});assert.equal(result.state,'not_accepted');assert.equal(budget(db,input.bindingId).spent_turns,0);assert.equal(budget(db,input.bindingId).active_turns,0);await controller.reconcile({...input,attemptId:attempt.id});assert.equal(budget(db,input.bindingId).spent_turns,0);assert.equal(store.receive(b).items.length,1);
});
test('off before submission cancels known-unsubmitted reservation without invoking driver',async t=>{
 const {store,db,b,input,driver,controller}=fixture(t),attempt=controller.reserve(input);store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});const stopped=await controller.reconcile({...input,attemptId:attempt.id});assert.equal(stopped.state,'not_submitted');assert.equal(budget(db,input.bindingId).spent_turns,0);assert.equal(budget(db,input.bindingId).active_turns,0);assert.equal(driver.calls.submit,0);assert.equal(store.receive(b).items.length,1);
});
test('cancel after acceptance requests interrupt and only confirmed stop releases concurrency',async t=>{
 const {store,db,a,q,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});store.requestTransition(a,q.id,1,'cancelled',{expectedTaskVersion:1});const stopped=await controller.reconcile({...input,attemptId:attempt.id});assert.equal(stopped.state,'stopped');assert.equal(stopped.attempt_stopped,true);assert.equal(budget(db,input.bindingId).active_turns,0);assert.equal(budget(db,input.bindingId).spent_turns,1);assert.equal(driver.calls.interrupt,1);assert.equal(store.requestGet(a,q.id).state,'cancelled');
});
test('unknown interrupt preserves budget and native fence; reconnect never repeats submission or interrupt',async t=>{
 const {store,db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});driver.setInterruptMode('unknown');store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});const unknown=await controller.reconcile({...input,attemptId:attempt.id});assert.equal(unknown.state,'unknown');assert.equal(unknown.attempt_stopped,'unknown');assert.equal(budget(db,input.bindingId).active_turns,1);await controller.reconcile({...input,attemptId:attempt.id});assert.equal(driver.calls.submit,1);assert.equal(driver.calls.interrupt,1);driver.setOutcome(attempt.id,'stopped');assert.equal((await controller.reconcile({...input,attemptId:attempt.id})).attempt_stopped,true);assert.equal(budget(db,input.bindingId).active_turns,0);
});
test('deadline and paused session interrupt a running mock turn without reactivating the request',async t=>{
 const {store,db,b,q,input,driver,controller,advance}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});db.prepare('UPDATE requests SET deadline_at=100001 WHERE id=?').run(q.id);advance(1);store.setSessionState(b,'paused');assert.equal((await controller.reconcile({...input,attemptId:attempt.id})).state,'stopped');assert.equal(driver.calls.submit,1);assert.equal(store.requestGet(b,q.id).state,'timed_out');
});
test('old owner epoch cannot observe or write callbacks for a newer binding',async t=>{
 const {db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});db.prepare('UPDATE native_bindings SET epoch=2 WHERE id=?').run(input.bindingId);await assert.rejects(()=>controller.reconcile({...input,attemptId:attempt.id}),/owner_epoch_conflict/);assert.equal(driver.calls.observe,0);assert.equal(budget(db,input.bindingId).active_turns,1);
});
test('a plain object claiming read-only native capabilities is not a trusted mock driver',t=>{
 const {db,clock,input,driver}=fixture(t);const impostor={...driver,kind:'read-only-mock'};assert.throws(()=>new ExecutionController(db,clock,impostor as typeof driver).reserve(input),/driver_unverified/);
});
test('busy or wrong native identity blocks reservations before any attempt is saved',t=>{
 const {db,input,driver,controller}=fixture(t);driver.setReadiness('busy');assert.throws(()=>controller.reserve(input),/host_busy/);driver.setReadiness('ready');const wrong=createMockDriver({bindingId:input.bindingId,epoch:1,instance:input.instance,profile:'different',nativeId:'owned-thread'});assert.throws(()=>new ExecutionController(db,{now:()=>100000},wrong).reserve(input),/driver_identity_mismatch/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);
});

test('lost mock host state stays unknown and cannot return a consumed turn or unlock delivery',async t=>{
 const {db,input,driver,controller}=fixture(t);driver.setSubmitMode('lose-response');const attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});const replacement=createMockDriver(driver.binding),reconnected=new ExecutionController(db,{now:()=>100000},replacement),unknown=await reconnected.reconcile({...input,attemptId:attempt.id});assert.equal(unknown.state,'unknown');assert.equal(budget(db,input.bindingId).spent_turns,1);assert.equal(budget(db,input.bindingId).active_turns,1);assert.equal(replacement.calls.submit,0);assert.equal(db.prepare('SELECT count(*) n FROM work_reservations').get()!.n,1);
});
test('failed stop-intent persistence never invokes interrupt or claims stopped',async t=>{
 const {store,db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});db.exec("CREATE TRIGGER fail_stop BEFORE UPDATE OF stop_requested ON work_attempts BEGIN SELECT RAISE(ABORT,'injected_stop_failure'); END");await assert.rejects(()=>controller.reconcile({...input,attemptId:attempt.id}),/injected_stop_failure/);assert.equal(driver.calls.interrupt,0);assert.equal(budget(db,input.bindingId).active_turns,1);
});
test('terminal observation is monotonic and repeated reconciliation never releases counters twice',async t=>{
 const {db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});driver.setOutcome(attempt.id,'succeeded');await controller.reconcile({...input,attemptId:attempt.id});driver.setOutcome(attempt.id,'unknown');assert.equal((await controller.reconcile({...input,attemptId:attempt.id})).state,'succeeded');assert.equal(budget(db,input.bindingId).active_turns,0);assert.equal(budget(db,input.bindingId).spent_turns,1);assert.equal(driver.calls.observe,1);
});
test('waiting for user approval retains native ownership and never approves or starts another turn',async t=>{
 const {store,db,a,b,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});driver.setOutcome(attempt.id,'waiting_user');assert.equal((await controller.reconcile({...input,attemptId:attempt.id})).state,'waiting_user');const next=store.requestCreate(a,{to:b.id,body:'next',key:'next',priority:'urgent',urgentReason:'test'});assert.throws(()=>controller.reserve({...input,messageId:next.message_id,key:'next'}),/host_busy/);assert.equal(driver.calls.submit,1);assert.equal(budget(db,input.bindingId).active_turns,1);
});
test('terminal observation after lease expiry preserves owner high-water across rollback',async t=>{
 const {store,db,a,b,input,driver,controller,advance}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});advance(60000);driver.setOutcome(attempt.id,'succeeded');await controller.reconcile({...input,attemptId:attempt.id});advance(-59000);const next=store.requestCreate(a,{to:b.id,body:'next',key:'next',priority:'urgent',urgentReason:'test'});assert.throws(()=>controller.reserve({...input,messageId:next.message_id,key:'next'}),/execution_unknown/);assert.equal(db.prepare('SELECT execution_state FROM native_bindings WHERE id=?').get(input.bindingId)!.execution_state,'unknown');
});
test('observed grant expiry and request deadline are durable before any peer read',async t=>{
 const {db,q,input,controller,advance}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});db.prepare('UPDATE managed_policies SET expires_at=100001 WHERE binding_id=?').run(input.bindingId);db.prepare('UPDATE requests SET deadline_at=100001 WHERE id=?').run(q.id);advance(1);await controller.reconcile({...input,attemptId:attempt.id});assert.equal(db.prepare('SELECT expired FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.expired,1);assert.equal(db.prepare('SELECT state FROM requests WHERE id=?').get(q.id)!.state,'timed_out');assert.equal(db.prepare('SELECT count(*) n FROM request_controls WHERE request_id=?').get(q.id)!.n,2);advance(-1);assert.equal(db.prepare('SELECT state FROM requests WHERE id=?').get(q.id)!.state,'timed_out');
});
test('an intent key recovers its original active attempt while the host is busy or policy is off',async t=>{
 const {store,db,input,driver,controller}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});assert.equal(controller.reserve(input).id,attempt.id);assert.equal(controller.reserve(input).state,'running');store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});assert.equal(controller.reserve(input).id,attempt.id);assert.throws(()=>controller.reserve({...input,messageId:'different'}),/idempotency_conflict/);assert.equal(driver.calls.submit,1);assert.equal(budget(db,input.bindingId).spent_turns,1);
});
test('intent replay observes owner expiry before returning an active snapshot',async t=>{
 const {store,db,a,b,input,driver,controller,advance}=fixture(t),attempt=controller.reserve(input);await controller.execute({...input,attemptId:attempt.id});advance(60000);assert.equal(controller.reserve(input).id,attempt.id);assert.equal(db.prepare('SELECT execution_state FROM native_bindings WHERE id=?').get(input.bindingId)!.execution_state,'unknown');advance(-59000);driver.setOutcome(attempt.id,'succeeded');await controller.reconcile({...input,attemptId:attempt.id});const next=store.requestCreate(a,{to:b.id,body:'next',key:'next',priority:'urgent',urgentReason:'test'});assert.throws(()=>controller.reserve({...input,messageId:next.message_id,key:'next'}),/execution_unknown/);
});
test('late lost submission response observes expiry before reconnect and clock rollback',async t=>{
 const {store,db,a,b,input,driver,controller,advance}=fixture(t);driver.setSubmitMode('lose-response');const attempt=controller.reserve(input),pending=controller.execute({...input,attemptId:attempt.id});for(let i=0;i<20&&!driver.calls.submit;i++)await Promise.resolve();assert.equal(driver.calls.submit,1);advance(60000);assert.equal((await pending).state,'unknown');assert.equal(db.prepare('SELECT execution_state FROM native_bindings WHERE id=?').get(input.bindingId)!.execution_state,'unknown');advance(-59000);driver.setOutcome(attempt.id,'succeeded');await controller.reconcile({...input,attemptId:attempt.id});const next=store.requestCreate(a,{to:b.id,body:'next',key:'next',priority:'urgent',urgentReason:'test'});assert.throws(()=>controller.reserve({...input,messageId:next.message_id,key:'next'}),/execution_unknown/);
});

function probeGate(driver:ReturnType<typeof createMockDriver>){let resolve!:(value:'ready'|'busy'|'unknown')=>void,reject!:(error:Error)=>void;const promise=new Promise<'ready'|'busy'|'unknown'>((yes,no)=>{resolve=yes;reject=no;}),gate={promise,resolve,reject};void gate.promise.catch(()=>{});driver.setReadiness(gate.promise);return gate;}
test('asynchronous reservation waits without charging budget or delivering input',async t=>{const {db,input,driver,controller}=fixture(t);assert.equal(typeof controller.reserveAsync,'function');const gate=probeGate(driver),pending=controller.reserveAsync(input);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);assert.equal(budget(db,input.bindingId).spent_turns,0);gate.resolve('ready');const attempt=await pending;assert.equal(attempt.state,'reserved');assert.equal(budget(db,input.bindingId).spent_turns,1);assert.equal(driver.calls.submit,0);});
for(const [label,reason,change] of [
 ['policy off','policy_off',(f:ReturnType<typeof fixture>)=>f.store.managedPolicy({bindingId:f.input.bindingId,version:2,enabled:false,key:'off'})],
 ['policy revision','policy_changed',(f:ReturnType<typeof fixture>)=>f.store.managedPolicy({bindingId:f.input.bindingId,version:2,enabled:true,key:'changed'})],
 ['grant expiry','grant_expired',(f:ReturnType<typeof fixture>)=>{f.db.prepare('UPDATE managed_policies SET expires_at=100001 WHERE binding_id=?').run(f.input.bindingId);f.advance(1);}],
 ['owner epoch','owner_epoch_conflict',(f:ReturnType<typeof fixture>)=>f.db.prepare('UPDATE native_bindings SET epoch=2 WHERE id=?').run(f.input.bindingId)],
 ['owner lease','execution_unknown',(f:ReturnType<typeof fixture>)=>f.advance(60000)],
 ['revocation','binding_revoked',(f:ReturnType<typeof fixture>)=>f.store.revoke(f.b.id)],
 ['pause','recipient_unavailable',(f:ReturnType<typeof fixture>)=>f.store.setSessionState(f.b,'paused')],
 ['deadline','trigger_unavailable',(f:ReturnType<typeof fixture>)=>{f.db.prepare('UPDATE requests SET deadline_at=100001 WHERE id=?').run(f.q.id);f.advance(1);}],
 ['source','source_changed',(f:ReturnType<typeof fixture>)=>f.db.prepare('UPDATE messages SET body=? WHERE id=?').run('changed',f.input.messageId)],
] as const)test('submission revalidates '+label+' after asynchronous readiness',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input),gate=probeGate(f.driver),pending=f.controller.execute({...f.input,attemptId:attempt.id});const rejected=assert.rejects(pending,new RegExp(reason));change(f);gate.resolve('ready');await rejected;assert.equal(f.driver.calls.submit,0);assert.equal(f.db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');assert.equal(f.db.prepare('SELECT delivered_at FROM messages WHERE id=?').get(f.input.messageId)!.delivered_at,null);assert.equal(budget(f.db,f.input.bindingId).active_turns,1);});
test('asynchronous reservation checks policy changes before charging',async t=>{const f=fixture(t);assert.equal(typeof f.controller.reserveAsync,'function');const gate=probeGate(f.driver),pending=f.controller.reserveAsync(f.input),rejected=assert.rejects(pending,/policy_off/);f.store.managedPolicy({bindingId:f.input.bindingId,version:2,enabled:false,key:'off'});gate.resolve('ready');await rejected;assert.equal(budget(f.db,f.input.bindingId).spent_turns,0);assert.equal(f.db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);});
test('readiness timeout quarantines a late ready response without submission',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input),gate=probeGate(f.driver);await assert.rejects(f.controller.execute({...f.input,attemptId:attempt.id}),/host_unknown/);gate.resolve('ready');await Promise.resolve();assert.equal(f.driver.calls.submit,0);assert.equal(f.db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');});
test('rejected readiness observes elapsed lease before returning unknown',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input),gate=probeGate(f.driver),pending=f.controller.execute({...f.input,attemptId:attempt.id}),rejected=assert.rejects(pending,/host_unknown/);f.advance(60000);gate.reject(new Error('probe failed'));await rejected;assert.equal(f.driver.calls.submit,0);assert.equal(f.db.prepare('SELECT execution_state FROM native_bindings WHERE id=?').get(f.input.bindingId)!.execution_state,'unknown');});

test('asynchronous replay returns the original attempt without another readiness probe',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input);await f.controller.execute({...f.input,attemptId:attempt.id});const gate=probeGate(f.driver);f.store.managedPolicy({bindingId:f.input.bindingId,version:2,enabled:false,key:'off'});assert.equal((await f.controller.reserveAsync(f.input)).id,attempt.id);assert.equal(f.driver.calls.submit,1);gate.resolve('unknown');});
test('concurrent asynchronous reservations of identical input charge only once',async t=>{const f=fixture(t),gate=probeGate(f.driver),first=f.controller.reserveAsync(f.input),second=f.controller.reserveAsync(f.input);gate.resolve('ready');const [a,b]=await Promise.all([first,second]);assert.equal(a.id,b.id);assert.equal(budget(f.db,f.input.bindingId).spent_turns,1);assert.equal(f.db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,1);});
test('explicit cancellation during readiness prevents a late submission',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input),gate=probeGate(f.driver),pending=f.controller.execute({...f.input,attemptId:attempt.id}),rejected=assert.rejects(pending,/submission_uncertain/);f.store.requestTransition(f.a,f.q.id,1,'cancelled',{expectedTaskVersion:1});assert.equal((await f.controller.reconcile({...f.input,attemptId:attempt.id})).state,'not_submitted');gate.resolve('ready');await rejected;assert.equal(f.driver.calls.submit,0);assert.equal(budget(f.db,f.input.bindingId).spent_turns,0);});
test('concurrent execution after shared readiness submits and records delivery once',async t=>{const f=fixture(t),attempt=f.controller.reserve(f.input),gate=probeGate(f.driver),first=f.controller.execute({...f.input,attemptId:attempt.id}),second=f.controller.execute({...f.input,attemptId:attempt.id});const results=Promise.allSettled([first,second]);gate.resolve('ready');const outcomes=await results;assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);const rejected=outcomes.find(r=>r.status==='rejected');assert.ok(rejected?.status==='rejected');assert.match(String(rejected.reason),/submission_uncertain/);assert.equal(f.driver.calls.submit,1);assert.equal(f.db.prepare('SELECT count(*) n FROM delivery_audit WHERE message_id=?').get(f.input.messageId)!.n,1);assert.equal(budget(f.db,f.input.bindingId).spent_turns,1);});
test('synchronous reservation refuses unresolved readiness without charging',t=>{const f=fixture(t),gate=probeGate(f.driver);assert.throws(()=>f.controller.reserve(f.input),/host_unknown/);assert.equal(budget(f.db,f.input.bindingId).spent_turns,0);assert.equal(f.db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);gate.resolve('ready');});
