import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createConnection,type Socket} from 'node:net';
import {OwnedPeerConnector} from '../src/owned-peer-connector.js';
import {OpencodeHttp} from '../src/opencode-http.js';
import {NativePeerInspector,NativePeerBuildError} from '../src/native-peer-inspector.js';
async function host(t:test.TestContext,fixedPort=0,acceptDelay=0){const child=spawn(process.execPath,['-e',"const net=require('node:net');const sockets=new Set();const server=net.createServer(socket=>{sockets.add(socket);console.log('accepted:'+socket.remotePort);socket.on('data',chunk=>console.log('bytes:'+chunk.length));socket.on('close',()=>sockets.delete(socket));});server.listen(Number(process.env.FIXTURE_PORT),'127.0.0.1',()=>{console.log('port:'+server.address().port);const until=Date.now()+Number(process.env.FIXTURE_DELAY);while(Date.now()<until){}});"],{stdio:['pipe','pipe','pipe'],env:{PATH:'/usr/bin:/bin',FIXTURE_PORT:String(fixedPort),FIXTURE_DELAY:String(acceptDelay)}});const closed=new Promise<void>(resolve=>child.once('close',()=>resolve()));child.stderr.resume();let buffer='',port:number|undefined,bytes=0;const accepted=new Set<number>();const waits=new Set<()=>void>();child.stdout.on('data',chunk=>{buffer+=chunk.toString();let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index);buffer=buffer.slice(index+1);if(line.startsWith('bytes:'))bytes+=Number(line.slice(6));if(line.startsWith('port:'))port=Number(line.slice(5));if(line.startsWith('accepted:'))accepted.add(Number(line.slice(9)));for(const done of waits)done();}});const until=async(check:()=>boolean)=>{if(check())return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{waits.delete(done);reject(new Error('fixture_timeout'));},3000),done=()=>{if(check()){clearTimeout(timer);waits.delete(done);resolve();}};waits.add(done);});};await until(()=>port!==undefined);const sockets:Socket[]=[];t.after(async()=>{for(const socket of sockets)socket.destroy();child.kill('SIGKILL');await closed;});return {pid:child.pid!,port:port!,get bytes(){return bytes;},get connections(){return accepted.size;},async stop(){child.kill('SIGKILL');await closed;},async connect(){const socket=createConnection({host:'127.0.0.1',port:port!});sockets.push(socket);await new Promise<void>((resolve,reject)=>{socket.once('connect',resolve);socket.once('error',reject);});await until(()=>accepted.has(socket.localPort!));return socket;}};}
const mac={skip:process.platform!=='darwin'};
test('kernel inspector verifies the exact owned accepted socket and rejects listener-only or wrong tuple',mac,async t=>{const inspector=await NativePeerInspector.build();t.after(()=>inspector.close());const h=await host(t),birth=await inspector.observeOwnedBirth(h.pid);assert.equal(birth.pid,h.pid);await assert.rejects(inspector.inspectOwnedPeer({birth,serverPort:h.port,clientPort:1}),/native_peer_unverified/);const socket=await h.connect();assert.deepEqual(await inspector.inspectOwnedPeer({birth,serverPort:h.port,clientPort:socket.localPort!}),{verified:true});await assert.rejects(inspector.inspectOwnedPeer({birth,serverPort:h.port,clientPort:socket.localPort! ===65535?1:socket.localPort!+1}),/native_peer_unverified/);await assert.rejects(inspector.inspectOwnedPeer({birth:{...birth,startMicros:birth.startMicros===999999?0:birth.startMicros+1},serverPort:h.port,clientPort:socket.localPort!}),/native_peer_unverified/);});
test('inspector rejects unrelated processes and invalid inputs without broader process inspection',mac,async t=>{const inspector=await NativePeerInspector.build();t.after(()=>inspector.close());await assert.rejects(inspector.observeOwnedBirth(process.pid),/native_peer_unverified/);for(const pid of [0,-1,1.5,2147483648])await assert.rejects(inspector.observeOwnedBirth(pid),/native_peer_invalid/);});
test('closed or departed ownership cannot inspect another connection',mac,async t=>{const inspector=await NativePeerInspector.build(),h=await host(t),birth=await inspector.observeOwnedBirth(h.pid),socket=await h.connect();await inspector.close();await inspector.close();await assert.rejects(inspector.inspectOwnedPeer({birth,serverPort:h.port,clientPort:socket.localPort!}),/native_peer_closed/);});
test('unsupported platform refuses kernel peer verification',{skip:process.platform==='darwin'},async()=>{await assert.rejects(NativePeerInspector.build(),/native_peer_unsupported/);});

test('replacement listener receives zero authentication bytes after original owned child departs',mac,async t=>{const inspector=await NativePeerInspector.build();t.after(()=>inspector.close());const original=await host(t),birth=await inspector.observeOwnedBirth(original.pid);await original.stop();const replacement=await host(t,original.port);const connector=new OwnedPeerConnector({port:replacement.port,timeoutMs:2000,assertLive:()=>{},verify:tuple=>inspector.inspectOwnedPeer({birth,...tuple}).then(()=>{})});const http=new OpencodeHttp({url:`http://127.0.0.1:${replacement.port}`,password:'x'.repeat(32),cwd:process.cwd(),timeoutMs:3000},connector);t.after(()=>http.close());await assert.rejects(http.call('health'),/http_transport_failed/);assert.equal(replacement.bytes,0);});
test('helper concurrency is bounded and concurrent close shares actual retirement',mac,async t=>{const inspector=await NativePeerInspector.build();t.after(()=>inspector.close());const h=await host(t);const calls=Array.from({length:9},()=>inspector.observeOwnedBirth(h.pid));const settled=Promise.allSettled(calls);const first=inspector.close(),second=inspector.close();assert.equal(first,second);await first;const results=await settled;assert.ok(results.some(result=>result.status==='rejected'&&String(result.reason).includes('native_peer_busy')));});

test('failed compiler retirement retains its cleanup handle for explicit retry',mac,async t=>{const original=process.kill;const mocked=t.mock.method(process,'kill',((pid:number,signal?:NodeJS.Signals|number)=>{if(pid<0)throw Object.assign(new Error('denied'),{code:'EPERM'});return original(pid,signal);}) as typeof process.kill);let retained:NativePeerInspector|undefined;try{await assert.rejects(NativePeerInspector.build(),error=>{assert.ok(error instanceof NativePeerBuildError);retained=error.inspector;return true;});}finally{mocked.mock.restore();await retained?.close();}assert.ok(retained);});

test('bounded read-only verification waits for acceptance on the same TCP stream',mac,async t=>{const inspector=await NativePeerInspector.build();t.after(()=>inspector.close());const h=await host(t,0,300),birth=await inspector.observeOwnedBirth(h.pid);const socket=createConnection({host:'127.0.0.1',port:h.port});t.after(()=>socket.destroy());await new Promise<void>((resolve,reject)=>{socket.once('connect',resolve);socket.once('error',reject);});assert.deepEqual(await inspector.waitOwnedPeer({birth,serverPort:h.port,clientPort:socket.localPort!},()=>{},1000),{verified:true});assert.equal(h.bytes,0);assert.equal(h.connections,1);});
