import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,statSync,symlinkSync,chmodSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {NativeProfileFence} from '../src/native-profile-fence.js';
function fixture(t:test.TestContext){const root=mkdtempSync(join(tmpdir(),'durebak-native-fence-')),profile=join(root,'profile');mkdirSync(profile,{mode:0o700});const fences:NativeProfileFence[]=[];t.after(()=>{for(const fence of fences)fence.close();rmSync(root,{recursive:true,force:true});});return {root,profile,hold:(fence:NativeProfileFence)=>{fences.push(fence);return fence;}};}
test('separate connections cannot own the same canonical profile',t=>{const {profile,hold}=fixture(t),fence=hold(NativeProfileFence.claim(profile,'driver-A'));assert.throws(()=>NativeProfileFence.claim(profile,'driver-B'),/native_owner_exists|native_profile_busy/);assert.equal(statSync(join(profile,'.durebak-owner.sqlite')).mode&0o777,0o600);assert.equal(fence.status().state,'owned');});
test('closing leaves durable unknown and never authorizes automatic takeover',t=>{const {profile,hold}=fixture(t),fence=hold(NativeProfileFence.claim(profile,'driver-A'));fence.recordNative('native-A');fence.close();const status=NativeProfileFence.inspect(profile);assert.equal(status.state,'unknown');assert.equal(status.native_id,'native-A');assert.throws(()=>NativeProfileFence.claim(profile,'driver-B'),/native_owner_exists/);assert.throws(()=>fence.recordNative('native-A'),/native_owner_closed/);});
test('native identity can only be recorded once for an open owner',t=>{const {profile,hold}=fixture(t),fence=hold(NativeProfileFence.claim(profile,'driver-A'));fence.recordNative('native-A');fence.recordNative('native-A');assert.throws(()=>fence.recordNative('native-B'),/native_identity_conflict/);assert.equal(fence.status().epoch,1);});
test('symlink and nonprivate profile/database paths are refused',t=>{const {root,profile}=fixture(t),alias=join(root,'alias');symlinkSync(profile,alias);assert.throws(()=>NativeProfileFence.claim(alias,'driver-A'),/native_profile_symlink/);assert.throws(()=>NativeProfileFence.claim(alias+'/','driver-A'),/native_profile_symlink/);chmodSync(profile,0o755);assert.throws(()=>NativeProfileFence.claim(profile,'driver-A'),/native_profile_not_private/);chmodSync(profile,0o700);const other=join(root,'other.sqlite');new DatabaseSync(other).close();symlinkSync(other,join(profile,'.durebak-owner.sqlite'));assert.throws(()=>NativeProfileFence.claim(profile,'driver-A'),/native_fence_unsafe/);});
test('ancestor aliases resolve to the same owner record',t=>{const {root,profile,hold}=fixture(t),link=join(root,'parent-alias');symlinkSync(root,link);const fence=hold(NativeProfileFence.claim(profile,'driver-A'));assert.throws(()=>NativeProfileFence.claim(join(link,'profile'),'driver-B'),/native_owner_exists|native_profile_busy/);});
test('ungraceful process exit remains unknown and cannot be reacquired',{timeout:10000},async t=>{const {profile}=fixture(t);const {spawn}=await import('node:child_process'),{fileURLToPath}=await import('node:url');const modulePath=fileURLToPath(new URL('../src/native-profile-fence.ts',import.meta.url));const child=spawn(process.execPath,['--import','tsx','--input-type=module','-e',`import {NativeProfileFence} from ${JSON.stringify(modulePath)};const f=NativeProfileFence.claim(${JSON.stringify(profile)},'child-owner');f.recordNative('child-native');process.stdout.write('owned\\n');setInterval(()=>{},1000);`],{stdio:['ignore','pipe','pipe']});const exited=new Promise(resolve=>child.once('exit',resolve));t.after(async()=>{if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await exited;});await new Promise<void>((resolve,reject)=>{child.stdout.once('data',()=>resolve());child.once('error',reject);child.once('exit',code=>reject(new Error('child_early_exit:'+code)));});assert.equal(NativeProfileFence.inspect(profile).state,'owned');assert.throws(()=>NativeProfileFence.claim(profile,'parent-owner'),/native_owner_exists/);child.kill('SIGKILL');await exited;assert.equal(NativeProfileFence.inspect(profile).state,'unknown');assert.throws(()=>NativeProfileFence.claim(profile,'parent-owner'),/native_owner_exists/);});
test('foreign and nonprivate existing owner databases are never adopted',t=>{const {profile}=fixture(t),file=join(profile,'.durebak-owner.sqlite'),foreign=new DatabaseSync(file);foreign.exec('CREATE TABLE unrelated(value TEXT)');foreign.close();chmodSync(file,0o600);assert.throws(()=>NativeProfileFence.claim(profile,'owner'),/native_owner_exists/);assert.throws(()=>NativeProfileFence.inspect(profile),/native_fence_invalid/);chmodSync(file,0o644);assert.throws(()=>NativeProfileFence.inspect(profile),/native_fence_unsafe/);});
test('inspection before initial lock acquisition sees unknown and cannot take over',t=>{const {profile,hold}=fixture(t),original=DatabaseSync.prototype.exec;let injected=false;DatabaseSync.prototype.exec=function(sql:string){if(sql==='BEGIN IMMEDIATE'&&!injected){injected=true;assert.equal(NativeProfileFence.inspect(profile).state,'unknown');}return original.call(this,sql);};try{const fence=hold(NativeProfileFence.claim(profile,'owner'));assert.equal(fence.status().state,'owned');assert.equal(NativeProfileFence.inspect(profile).state,'owned');}finally{DatabaseSync.prototype.exec=original;}});
test('inspection during native identity commit never revokes a live owner',t=>{const {profile,hold}=fixture(t),fence=hold(NativeProfileFence.claim(profile,'owner')),original=DatabaseSync.prototype.exec;let observed:string|undefined;DatabaseSync.prototype.exec=function(sql:string){const result=original.call(this,sql);if(sql==='COMMIT'&&observed===undefined){observed='checking';observed=NativeProfileFence.inspect(profile).state;}return result;};try{fence.recordNative('native-A');assert.equal(observed,'owned');assert.equal(NativeProfileFence.inspect(profile).state,'owned');}finally{DatabaseSync.prototype.exec=original;}});
test('a metadata reader blocking unknown persistence never produces owned after holder loss',t=>{const {profile,hold}=fixture(t),fence=hold(NativeProfileFence.claim(profile,'owner'));(fence as unknown as {lock:DatabaseSync}).lock.exec('ROLLBACK');const reader=new DatabaseSync(join(profile,'.durebak-owner.sqlite'));reader.exec('BEGIN');reader.prepare('SELECT * FROM owner').get();try{assert.throws(()=>NativeProfileFence.inspect(profile),/native_fence_invalid/);}finally{reader.exec('ROLLBACK');reader.close();}assert.equal(NativeProfileFence.inspect(profile).state,'unknown');fence.close();});
test('symlink ancestor with dot traversal fences the actual filesystem profile',t=>{const {root,profile,hold}=fixture(t),other=join(root,'x','profile');mkdirSync(join(root,'x','y'),{recursive:true,mode:0o700});mkdirSync(other,{mode:0o700});symlinkSync(join(root,'x','y'),join(root,'alias'));const fence=hold(NativeProfileFence.claim(join(root,'alias')+'/../profile','owner-A'));assert.equal(fence.status().state,'owned');assert.throws(()=>NativeProfileFence.claim(other,'owner-B'),/native_owner_exists/);hold(NativeProfileFence.claim(profile,'independent-owner'));});
