import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,realpathSync,rmSync,chmodSync,symlinkSync,writeFileSync,linkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {createServer} from 'node:net';
import {compileNativeBootstrap,nativeBootstrapCommand} from '../src/native-bootstrap-sandbox.js';
function fixture(){const root=realpathSync.native(mkdtempSync(join(tmpdir(),'durebak-bootstrap-')));const paths=Object.fromEntries(['runtime','input','owner'].map(name=>{const path=join(root,name);mkdirSync(path,{mode:0o700});return [name,path];}));const binary=join(root,'binary');writeFileSync(binary,'synthetic',{mode:0o700});return {root,options:{binary,runtimeRoot:paths.runtime!,inputRoot:paths.input!,ownerProfile:paths.owner!,port:12345},close(){rmSync(root,{recursive:true,force:true});}};}
test('compile a deny-default bootstrap policy with exact loopback port and separate owner ledger',()=>{const f=fixture();try{const result=compileNativeBootstrap(f.options);assert.equal(result.cwd,f.options.inputRoot);assert.equal(result.binary,f.options.binary);assert.match(result.policy,/\(deny default\)/);assert.ok(result.policy.includes('localhost:12345'));assert.ok(!result.policy.includes('network-outbound'));assert.ok(!result.policy.includes(f.options.ownerProfile));assert.ok(!result.policy.includes('(allow process*)'));assert.ok(!result.policy.includes('(allow sysctl-read)'));assert.ok(!result.policy.includes('(subpath "/private/var/db")'));}finally{f.close();}});
test('reject overlapping runtime, input and owner directories',()=>{const f=fixture();try{for(const options of [{...f.options,ownerProfile:f.options.runtimeRoot},{...f.options,runtimeRoot:f.root},{...f.options,inputRoot:f.options.runtimeRoot}])assert.throws(()=>compileNativeBootstrap(options),/native_bootstrap_invalid/);}finally{f.close();}});
test('reject unsafe private directory modes and direct symlinks including trailing slash',()=>{const f=fixture();try{chmodSync(f.options.runtimeRoot,0o755);assert.throws(()=>compileNativeBootstrap(f.options),/native_bootstrap_invalid/);chmodSync(f.options.runtimeRoot,0o700);const alias=join(f.root,'alias');symlinkSync(f.options.runtimeRoot,alias);for(const runtimeRoot of [alias,alias+'/'])assert.throws(()=>compileNativeBootstrap({...f.options,runtimeRoot}),/native_bootstrap_invalid/);}finally{f.close();}});
test('reject writable-root executable overlap, non-executable files, hardlinks and symlinks',()=>{const f=fixture();try{const inside=join(f.options.runtimeRoot,'binary');writeFileSync(inside,'synthetic',{mode:0o700});assert.throws(()=>compileNativeBootstrap({...f.options,binary:inside}),/native_bootstrap_invalid/);chmodSync(f.options.binary,0o600);assert.throws(()=>compileNativeBootstrap(f.options),/native_bootstrap_invalid/);chmodSync(f.options.binary,0o700);const alias=join(f.root,'alias');symlinkSync(f.options.binary,alias);assert.throws(()=>compileNativeBootstrap({...f.options,binary:alias}),/native_bootstrap_invalid/);linkSync(f.options.binary,join(f.root,'hardlink'));assert.throws(()=>compileNativeBootstrap(f.options),/native_bootstrap_invalid/);}finally{f.close();}});
test('schema errors and path content cannot introduce extra policy or private diagnostics',()=>{const f=fixture();try{for(const raw of [{...f.options,port:0},{...f.options,port:65536},{...f.options,port:1.1},{...f.options,policy:'PRIVATE'},{...f.options,inputRoot:'PRIVATE\n(allow default)'},{...f.options,runtimeRoot:'relative'}])assert.throws(()=>compileNativeBootstrap(raw),e=>e instanceof Error&&e.message==='native_bootstrap_invalid');}finally{f.close();}});
test('quote-bearing canonical directories are escaped as policy strings',()=>{const f=fixture();try{const inputRoot=join(f.root,'input"quoted');mkdirSync(inputRoot,{mode:0o700});const result=compileNativeBootstrap({...f.options,inputRoot});assert.ok(result.policy.includes(JSON.stringify(inputRoot)));assert.equal(result.cwd,inputRoot);}finally{f.close();}});
test('unsupported platform cannot fall back to an unsandboxed command',()=>{const f=fixture();try{if(process.platform!=='darwin')assert.throws(()=>nativeBootstrapCommand(f.options),/native_bootstrap_unsupported/);else{const result=nativeBootstrapCommand(f.options);assert.equal(result.command,'/usr/bin/sandbox-exec');assert.deepEqual(result.args,['-p',compileNativeBootstrap(f.options).policy,f.options.binary]);assert.ok(Object.isFrozen(result.args));}}finally{f.close();}});

test('macOS compiled boundary rejects outside, owner, symlink, descendant and outbound access while allowing selected input and inbound contact',{skip:process.platform!=='darwin',timeout:15000},async()=>{
 const f=fixture();const outside=join(f.root,'outside'),owner=join(f.options.ownerProfile,'private'),allowed=join(f.options.inputRoot,'allowed');writeFileSync(outside,'SYNTHETIC_OUTSIDE');writeFileSync(owner,'SYNTHETIC_OWNER');writeFileSync(allowed,'SYNTHETIC_INPUT');
 const inbound=createServer();await new Promise<void>(resolve=>inbound.listen(0,'127.0.0.1',resolve));const port=(inbound.address() as {port:number}).port;await new Promise<void>(resolve=>inbound.close(()=>resolve()));
 const forbidden=createServer();await new Promise<void>(resolve=>forbidden.listen(0,'127.0.0.1',resolve));const other=(forbidden.address() as {port:number}).port;
 const selected=nativeBootstrapCommand({...f.options,binary:realpathSync.native(process.execPath),port});symlinkSync(outside,join(f.options.inputRoot,'escape'));
 const code=`const fs=require('node:fs'),net=require('node:net'),{execFileSync}=require('node:child_process');console.error('STAGE_BEGIN');const [allowed,outside,owner,escape,write,link,port,other]=process.argv.slice(1);const denied=f=>{try{f();return false;}catch(e){return e.code==='EPERM';}};const report={allowed:fs.readFileSync(allowed,'utf8')==='SYNTHETIC_INPUT',outside:denied(()=>fs.readFileSync(outside)),owner:denied(()=>fs.readFileSync(owner)),symlink:denied(()=>fs.readFileSync(escape)),outsideWrite:denied(()=>fs.writeFileSync(outside,'CHANGED')),hardlink:denied(()=>fs.linkSync(outside,link))};fs.writeFileSync(write,'SYNTHETIC_WRITE');report.allowedWrite=true;try{execFileSync('/bin/cat',[outside],{stdio:'pipe',timeout:2000});report.descendant=false;}catch(e){report.descendant=e.status!==null&&e.status!==0;}console.error('STAGE_FILES');const socket=net.connect({host:'127.0.0.1',port:Number(other)});socket.once('error',e=>{console.error('STAGE_OUTBOUND_'+e.code);report.outbound=e.code==='EPERM';const server=net.createServer(c=>{report.inbound=true;c.end();server.close(()=>console.log(JSON.stringify(report)));});server.listen(Number(port),'127.0.0.1',()=>console.error('READY'));});socket.setTimeout(1500,()=>{socket.destroy();process.exitCode=1;});`;
 const child=spawn(selected.command,[...selected.args,'-e',code,allowed,outside,owner,join(f.options.inputRoot,'escape'),join(f.options.inputRoot,'write'),join(f.options.inputRoot,'hardlink'),String(port),String(other)],{cwd:selected.cwd,env:{PATH:'/usr/bin:/bin',TMPDIR:f.options.runtimeRoot},detached:true,stdio:['pipe','pipe','pipe']});let output='',stderr='',connected=false;child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>{stderr+=chunk;if(!connected&&stderr.includes('READY')){connected=true;import('node:net').then(({connect})=>{const peer=connect({host:'127.0.0.1',port});peer.on('error',()=>{});peer.on('end',()=>peer.destroy());});}});
 try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('canary_timeout:'+stderr)),8000);child.once('error',error=>{clearTimeout(timer);reject(error);});child.once('close',code=>{clearTimeout(timer);code===0?resolve():reject(new Error('canary_failed:'+code+':'+stderr));});});const result=JSON.parse(output);assert.deepEqual(result,{allowed:true,outside:true,owner:true,symlink:true,outsideWrite:true,hardlink:true,allowedWrite:true,descendant:true,outbound:true,inbound:true});}
 finally{try{process.kill(-child.pid!,'SIGKILL');}catch(error){if((error as NodeJS.ErrnoException).code!=='ESRCH')throw error;}await new Promise<void>(resolve=>forbidden.close(()=>resolve()));f.close();}
});

test('pre-existing hardlink aliases from outside or owner cannot be adopted into writable trees',()=>{const f=fixture();try{const outside=join(f.root,'outside');writeFileSync(outside,'SYNTHETIC');linkSync(outside,join(f.options.inputRoot,'alias'));assert.throws(()=>compileNativeBootstrap(f.options),/native_bootstrap_invalid/);}finally{f.close();}const second=fixture();try{const owner=join(second.options.ownerProfile,'record');writeFileSync(owner,'SYNTHETIC');linkSync(owner,join(second.options.runtimeRoot,'alias'));assert.throws(()=>compileNativeBootstrap(second.options),/native_bootstrap_invalid/);}finally{second.close();}});
test('unsafe or unbounded staged trees are rejected before a command is returned',()=>{const f=fixture();try{symlinkSync(f.options.ownerProfile,join(f.options.inputRoot,'alias'));assert.throws(()=>compileNativeBootstrap(f.options),/native_bootstrap_invalid/);}finally{f.close();}const second=fixture();try{for(let i=0;i<1025;i++)writeFileSync(join(second.options.inputRoot,String(i)),'SYNTHETIC');assert.throws(()=>compileNativeBootstrap(second.options),/native_bootstrap_invalid/);}finally{second.close();}});

test('macOS process argument/environment access has a synthetic positive control and exact EPERM denial',{skip:process.platform!=='darwin',timeout:20000},async()=>{
 const f=fixture();const helper=join(f.options.runtimeRoot,'sysctl-canary');const source=String.raw`#include <sys/types.h>
#include <sys/sysctl.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
int main(int argc,char **argv){if(argc!=2)return 2;if(strcmp(argv[1],"--target")==0){puts(getenv("DUREBAK_CANARY_MARKER")?"READY":"NO_MARKER");fflush(stdout);sleep(30);return 0;}int mib[3]={CTL_KERN,KERN_PROCARGS2,(int)strtol(argv[1],NULL,10)};char bytes[65536];size_t size=sizeof(bytes);if(sysctl(mib,3,bytes,&size,NULL,0)!=0){printf("{\"read\":false,\"errno\":%d}\n",errno);return 0;}const char marker[]="DUREBAK_CANARY_MARKER=SYNTHETIC_PROCESS_MARKER";int found=0;for(size_t i=0;i+sizeof(marker)-1<=size;i++)if(memcmp(bytes+i,marker,sizeof(marker)-1)==0){found=1;break;}printf("{\"read\":true,\"marker\":%s}\n",found?"true":"false");return 0;}`;
 let target:ReturnType<typeof spawn>|undefined;
 try{execFileSync('/usr/bin/cc',['-x','c','-','-o',helper],{input:source,env:{PATH:'/usr/bin:/bin',TMPDIR:f.options.runtimeRoot},timeout:10000,stdio:['pipe','pipe','pipe']});target=spawn(helper,['--target'],{env:{DUREBAK_CANARY_MARKER:'SYNTHETIC_PROCESS_MARKER'},detached:true,stdio:['ignore','pipe','pipe']});await new Promise<void>((resolve,reject)=>{target!.stdout!.once('data',data=>data.toString().trim()==='READY'?resolve():reject(new Error('canary_marker_missing')));target!.once('error',reject);});const pid=String(target.pid);const positive=JSON.parse(execFileSync(helper,[pid],{encoding:'utf8',timeout:2000}));assert.deepEqual(positive,{read:true,marker:true});const selected=nativeBootstrapCommand({...f.options,binary:realpathSync.native(process.execPath)});const code="const {execFileSync}=require('node:child_process');console.log(execFileSync(process.argv[1],[process.argv[2]],{encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim());";const denied=JSON.parse(execFileSync(selected.command,[...selected.args,'-e',code,helper,pid],{encoding:'utf8',env:{PATH:'/usr/bin:/bin',TMPDIR:f.options.runtimeRoot},cwd:selected.cwd,timeout:3000}));assert.deepEqual(denied,{read:false,errno:1});}
 finally{if(target?.pid){const closed=new Promise<void>(resolve=>{if(target!.exitCode!==null||target!.signalCode!==null)resolve();else target!.once('close',()=>resolve());});try{process.kill(-target.pid,'SIGKILL');}catch(error){if((error as NodeJS.ErrnoException).code!=='ESRCH')throw error;}await closed;}f.close();}
});
