import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,realpathSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {NativePeerInspector} from '../src/native-peer-inspector.js';
import {NativeProfileFence} from '../src/native-profile-fence.js';
import {startOwnedOpencodeHost,OwnedOpencodeCleanupError} from '../src/opencode-owned-host.js';
const supported={skip:process.platform!=='darwin'};
function fixture(t:test.TestContext,mode='normal'){
 const root=realpathSync.native(mkdtempSync(join(tmpdir(),'durebak-owned-opencode-'))),profile=join(root,'owner'),runtimeRoot=join(root,'runtime'),cwd=join(root,'input'),binary=join(root,'native-fixture.cjs');for(const path of [profile,runtimeRoot,cwd])mkdirSync(path,{mode:0o700});
 writeFileSync(binary,`#!${process.execPath}
const {createServer}=require('node:http');
const {readFileSync,writeFileSync}=require('node:fs');
const {join}=require('node:path');
(async()=>{
const mode=${JSON.stringify(mode)},state=process.env.XDG_STATE_HOME,tracePath=join(state,'trace.json');
const trace={pid:process.pid,env:Object.keys(process.env).sort(),calls:[],bodies:[],announced:false};const save=()=>writeFileSync(tracePath,JSON.stringify(trace),{mode:0o600});save();
const args=process.argv.slice(2),port=Number(args[args.indexOf('--port')+1]);if(args[0]!=='serve'||args[args.indexOf('--hostname')+1]!=='127.0.0.1'||!port)process.exit(4);
const config=JSON.parse(process.env.OPENCODE_CONFIG_CONTENT),deny=[{permission:'*',pattern:'*',action:'deny'}];
let session;
if(mode==='descendant'||mode==='pipes'){const {spawn}=require('node:child_process');const ready=join(state,'helper-pid');const helper=spawn(process.execPath,['-e',"process.on('SIGTERM',()=>{});setInterval(()=>{},1000);require('node:fs').writeFileSync(process.argv[1],String(process.pid));",ready],{stdio:mode==='pipes'?['pipe','inherit','inherit']:['pipe','pipe','pipe']});helper.stdin.end();helper.stdout?.resume();helper.stderr?.resume();while(!(()=>{try{return !!readFileSync(ready,'utf8');}catch{return false;}})())await new Promise(r=>setTimeout(r,5));}
if(mode==='ignore-term')process.on('SIGTERM',()=>{});
const server=createServer((req,res)=>{const url=new URL(req.url,'http://localhost');trace.calls.push(url.pathname);save();if(req.headers.authorization!=='Basic '+Buffer.from('opencode:'+process.env.OPENCODE_SERVER_PASSWORD).toString('base64')||url.searchParams.get('directory')!==process.cwd()){res.writeHead(401);res.end();return;}if(mode==='silence')return;let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{let value;if(url.pathname==='/global/health')value={healthy:true,version:mode==='version'?'0.0.0':'1.18.34'};else if(url.pathname==='/config')value={...config,...((mode==='config'||mode==='late-config'&&trace.calls.filter(path=>path==='/config').length>1)?{share:'auto'}:{})};else if(url.pathname==='/mcp')value=(mode==='mcp'||mode==='late-mcp'&&trace.calls.filter(path=>path==='/mcp').length>1)?{foreign:{status:'connected'}}:{};else if(url.pathname==='/session/status')value=mode==='busy'?{ses_fresh:{type:'busy'}}:mode==='foreign-status'&&session?{ses_foreign:{type:'busy'}}:mode==='late-sibling'&&trace.calls.filter(path=>path==='/session').length>3?{ses_foreign:{type:'busy'}}:{};else if(url.pathname==='/session'&&req.method==='POST'){const parsed=JSON.parse(body);trace.bodies.push(parsed);save();session={id:'ses_fresh',slug:'synthetic',projectID:'global',directory:process.cwd(),title:parsed.title,agent:parsed.agent,model:parsed.model,permission:parsed.permission,metadata:parsed.metadata,version:'1.18.34',time:{created:1,updated:1}};if(mode==='marker')session.metadata={durebakOwner:'foreign'};if(mode==='permission')session.permission=[];if(mode==='model')session.model={id:'foreign',providerID:'opencode'};if(mode==='directory')session.directory=state;if(mode==='parent')session.parentID='ses_foreign';if(mode==='share')session.share={url:'https://example.invalid'};value=session;}else if(url.pathname==='/session')value=mode==='existing'?[{id:'ses_existing'}]:session?(mode==='extra-session'||mode==='late-sibling'&&trace.calls.filter(path=>path==='/session').length>3?[session,{...session,id:'ses_foreign'}]:[session]):[];else if(url.pathname==='/session/ses_fresh')value=session;else if(url.pathname==='/session/ses_fresh/message')value=mode==='history'?[{info:{id:'msg_foreign'}}]:[];else if(url.pathname==='/provider')value={all:[{id:'opencode',models:{'big-pickle':{id:'big-pickle'}}}],connected:['opencode'],default:{}};else{res.writeHead(404);res.end('{}');return;}res.setHeader('content-type','application/json');const reply=()=>{if(url.pathname==='/config'){trace.config_replied=true;save();}res.end(JSON.stringify(value));};if(mode==='global-deadline'&&url.pathname==='/global/health')setTimeout(reply,1600);else if(mode==='global-deadline'&&url.pathname==='/config')setTimeout(reply,2200);else reply();});});
if(mode==='bind-conflict'){const blocker=createServer((req,res)=>{trace.calls.push('foreign-endpoint');save();res.end('{}');});await new Promise(resolve=>blocker.listen(port,'127.0.0.1',resolve));server.on('error',()=>process.exit(8));}
if(mode==='overflow'){console.log('x'.repeat(70000));setInterval(()=>{},1000);}else server.listen(port,'127.0.0.1',()=>{if(mode==='no-announcement')return;trace.announced=true;save();console.log('opencode server listening on http://127.0.0.1:'+(mode==='wrong-announcement'?port+1:port));});
})().catch(()=>process.exit(7));
`,{mode:0o700});
 const hosts:Awaited<ReturnType<typeof startOwnedOpencodeHost>>[]=[];t.after(async()=>{for(const host of hosts)await host.close();const helperPath=join(runtimeRoot,'state','helper-pid');if(existsSync(helperPath)){try{process.kill(Number(readFileSync(helperPath,'utf8')),'SIGKILL');}catch{}}rmSync(root,{recursive:true,force:true});});return {profile,runtimeRoot,cwd,binary,options:{binary,runtimeRoot,profile,cwd,instance:'owner',providerId:'opencode',modelId:'big-pickle',timeoutMs:5000,shutdownMs:300},hold(host:Awaited<ReturnType<typeof startOwnedOpencodeHost>>){hosts.push(host);return host;},trace(){return JSON.parse(readFileSync(join(runtimeRoot,'state','trace.json'),'utf8')) as {pid:number;env:string[];calls:string[];bodies:any[];announced:boolean;config_replied?:boolean};}};
}
test('owned OpenCode bootstrap creates one fresh scoped session without model authority',supported,async t=>{const f=fixture(t),host=f.hold(await startOwnedOpencodeHost(f.options));assert.equal(host.metadata.nativeId,'ses_fresh');assert.equal(host.metadata.model_verified,false);assert.equal(host.metadata.auto_wake,false);assert.equal(host.metadata.connected_peer_verified,true);assert.equal(NativeProfileFence.inspect(f.profile).state,'owned');assert.equal(NativeProfileFence.inspect(f.profile).native_id,'ses_fresh');assert.equal(f.trace().announced,true);assert.equal(f.trace().calls[0],'/global/health');assert.equal(f.trace().bodies.length,1);assert.deepEqual(f.trace().bodies[0].permission,[{permission:'*',pattern:'*',action:'deny'}]);assert.equal(f.trace().env.includes('OPENAI_API_KEY'),false);assert.equal(f.trace().env.includes('DUREBAK_SESSION_FILE'),false);assert.equal('attach' in host,false);assert.equal('submit' in host,false);const health=await host.health();assert.equal(health.contact,'ready');assert.equal(health.entitlement,'unverified');assert.equal(f.trace().calls.some(path=>path.includes('prompt')||path.includes('abort')),false);});
for(const mode of ['version','config','mcp','existing','marker','permission','model','directory','parent','share','history','busy','silence','wrong-announcement','no-announcement','overflow','bind-conflict','extra-session','foreign-status'])test('owned bootstrap refuses '+mode+' and confirms group retirement',supported,async t=>{const f=fixture(t,mode);await assert.rejects(startOwnedOpencodeHost(f.options).then(host=>f.hold(host)),/native_host_bootstrap_failed/);const trace=f.trace();assert.throws(()=>process.kill(trace.pid,0));assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');assert.equal(trace.calls.some(path=>path.includes('prompt')||path.includes('abort')),false);if(['wrong-announcement','no-announcement','overflow','bind-conflict'].includes(mode))assert.deepEqual(trace.calls,[]);});
test('closed host cannot retain readiness and old owner cannot start a new host',supported,async t=>{const f=fixture(t),host=f.hold(await startOwnedOpencodeHost(f.options)),pid=f.trace().pid;await host.close();await host.close();assert.throws(()=>process.kill(pid,0));assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');await assert.rejects(host.health(),/native_host_closed/);await assert.rejects(startOwnedOpencodeHost({...f.options,runtimeRoot:f.cwd,cwd:f.runtimeRoot}));});
for(const mode of ['ignore-term','descendant','pipes'])test('owned close confirms '+mode+' process group disappearance',supported,async t=>{const f=fixture(t,mode),host=f.hold(await startOwnedOpencodeHost(f.options)),pid=f.trace().pid;await host.close();assert.throws(()=>process.kill(-pid,0));assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});
test('unsupported platform never starts an unconfined native process',{skip:process.platform==='darwin'},async t=>{const f=fixture(t);await assert.rejects(startOwnedOpencodeHost(f.options),/native_bootstrap_unsupported/);assert.equal(existsSync(join(f.profile,'.durebak-owner.sqlite')),false);});

test('one overall bootstrap deadline closes the pending configuration read',supported,async t=>{const f=fixture(t,'global-deadline');await assert.rejects(startOwnedOpencodeHost({...f.options,timeoutMs:3000}),/native_host_bootstrap_failed/);assert.ok(f.trace().calls.includes('/config'));assert.equal(f.trace().config_replied,undefined);assert.equal(f.trace().bodies.length,0);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});
test('changed configuration retires readiness without exposing native data',supported,async t=>{const f=fixture(t,'late-config'),host=f.hold(await startOwnedOpencodeHost(f.options));await assert.rejects(host.health(),e=>e instanceof Error&&e.message==='native_health_invalid');await assert.rejects(host.health(),/native_host_closed/);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});
test('leader exit retires readiness while inherited pipes remain open',supported,async t=>{const f=fixture(t,'pipes'),host=f.hold(await startOwnedOpencodeHost(f.options));process.kill(f.trace().pid,'SIGTERM');await new Promise(r=>setTimeout(r,100));await assert.rejects(host.health(),/native_host_closed/);await host.close();assert.throws(()=>process.kill(-f.trace().pid,0));assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});
test('uncertain group inspection retains ownership until explicit cleanup retry',supported,async t=>{const f=fixture(t),host=f.hold(await startOwnedOpencodeHost(f.options)),pid=f.trace().pid,kill=process.kill.bind(process);const mocked=t.mock.method(process,'kill',(target:number,signal?:NodeJS.Signals|number)=>{if(target===-pid)throw Object.assign(new Error('group inspection denied'),{code:'EPERM'});return kill(target,signal);});try{await assert.rejects(host.close(),/native_shutdown_timeout/);assert.equal(NativeProfileFence.inspect(f.profile).state,'owned');await assert.rejects(host.health(),/native_host_closed/);}finally{mocked.mock.restore();await host.close();}assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});

test('new foreign sibling during health retires the owned scope',supported,async t=>{const f=fixture(t,'late-sibling'),host=f.hold(await startOwnedOpencodeHost(f.options));await assert.rejects(host.health(),e=>e instanceof Error&&e.message==='native_health_invalid');await assert.rejects(host.health(),/native_host_closed/);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});

test('new MCP state during health retires the owned scope',supported,async t=>{const f=fixture(t,'late-mcp'),host=f.hold(await startOwnedOpencodeHost(f.options));await assert.rejects(host.health(),e=>e instanceof Error&&e.message==='native_health_invalid');await assert.rejects(host.health(),/native_host_closed/);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});

test('birth observation cannot extend the overall bootstrap deadline',supported,async t=>{const f=fixture(t);let observed=false;t.mock.method(NativePeerInspector.prototype,'observeOwnedBirth',async()=>{observed=true;return new Promise(()=>{});});const started=Date.now();await assert.rejects(startOwnedOpencodeHost({...f.options,timeoutMs:700}),/native_host_bootstrap_failed/);assert.equal(observed,true);assert.ok(Date.now()-started<2500);assert.equal(f.trace().calls.length,0);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});

test('factory preserves the fence and explicit cleanup retry after compiler uncertainty',supported,async t=>{const f=fixture(t),original=process.kill;const mocked=t.mock.method(process,'kill',((pid:number,signal?:NodeJS.Signals|number)=>{if(pid<0)throw Object.assign(new Error('denied'),{code:'EPERM'});return original(pid,signal);}) as typeof process.kill);let retained:OwnedOpencodeCleanupError|undefined;try{await assert.rejects(startOwnedOpencodeHost(f.options),error=>{assert.ok(error instanceof OwnedOpencodeCleanupError);retained=error;return true;});assert.equal(NativeProfileFence.inspect(f.profile).state,'owned');}finally{mocked.mock.restore();await retained?.close();}assert.ok(retained);assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');});

test('group disappearance is retained while pipe closure and explicit cleanup retry are pending',supported,async t=>{const f=fixture(t,'pipes'),host=f.hold(await startOwnedOpencodeHost({...f.options,shutdownMs:50})),pid=f.trace().pid,original=process.kill.bind(process);let gone=false,signalsAfterGone=0;const mocked=t.mock.method(process,'kill',(target:number,signal?:NodeJS.Signals|number)=>{if(target===-pid){if(signal===0){if(!gone){gone=true;throw Object.assign(new Error('original gone'),{code:'ESRCH'});}return true;}if(gone){signalsAfterGone++;return true;}}return original(target,signal);});try{await assert.rejects(host.close());assert.equal(signalsAfterGone,0);assert.equal(NativeProfileFence.inspect(f.profile).state,'owned');original(-pid,'SIGKILL');const deadline=Date.now()+2000;while(true){try{original(-pid,0);}catch(error){if((error as NodeJS.ErrnoException).code==='ESRCH')break;throw error;}if(Date.now()>=deadline)throw new Error('fixture_group_timeout');await new Promise(resolve=>setTimeout(resolve,10));}await host.close();assert.equal(NativeProfileFence.inspect(f.profile).state,'unknown');}finally{mocked.mock.restore();try{original(-pid,'SIGKILL');}catch{}await host.close();}assert.equal(signalsAfterGone,0);});
