import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtempSync,mkdirSync,rmSync,realpathSync,statSync,symlinkSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {NativeProfileFence} from '../src/native-profile-fence.js';
import {OpencodeHttp} from '../src/opencode-http.js';
import {OpencodeTurns} from '../src/opencode-turns.js';
import {hash} from '../src/domain.js';
function gate(){let open!:()=>void;const promise=new Promise<void>(resolve=>{open=resolve;});return {promise,open};}
type Message={info:Record<string,unknown>;parts:Record<string,unknown>[]};
async function fixture(t:test.TestContext){
 const root=mkdtempSync(join(tmpdir(),'durebak-opencode-turns-')),profile=join(root,'profile'),input=join(root,'input');mkdirSync(profile,{mode:0o700});mkdirSync(input,{mode:0o700});const cwd=realpathSync.native(input),fence=NativeProfileFence.claim(profile,'owner');fence.recordNative('ses_owned');
 const state={history:[] as Message[],posts:0,aborts:0,loseReceipt:false,healthGate:null as ReturnType<typeof gate>|null,submitGate:null as ReturnType<typeof gate>|null,submitStarted:gate(),abortGate:null as ReturnType<typeof gate>|null,abortStarted:gate(),loseAbortReceipt:false,foreignSession:false,beforePost:()=>{},abortStops:false};
 const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const path=new URL(req.url!,'http://127.0.0.1').pathname;res.setHeader('content-type','application/json');
  if(path==='/global/health'){if(state.healthGate)await state.healthGate.promise;res.end(JSON.stringify({healthy:true,version:'1.18.34'}));}
  else if(path==='/session/ses_owned'){res.end(JSON.stringify({id:state.foreignSession?'ses_foreign':'ses_owned',directory:cwd}));}
  else if(path==='/session/ses_owned/message'){res.end(JSON.stringify(state.history));}
  else if(path==='/session/ses_owned/prompt_async'){state.posts++;state.beforePost();state.submitStarted.open();if(state.submitGate)await state.submitGate.promise;const data=JSON.parse(body);state.history.push({info:{id:data.messageID,sessionID:'ses_owned',role:'user',model:data.model},parts:data.parts.map((part:Record<string,unknown>,i:number)=>({...part,id:'part_input'+i,sessionID:'ses_owned',messageID:data.messageID}))});if(state.loseReceipt)req.socket.destroy();else{res.statusCode=204;res.end();}}
  else if(path==='/session/ses_owned/abort'){state.aborts++;state.abortStarted.open();if(state.abortGate)await state.abortGate.promise;if(state.abortStops){const user=[...state.history].reverse().find(m=>m.info.role==='user')!;state.history=state.history.filter(m=>m.info.id!=='msg_answer');state.history.push(answer(user.info.id as string,'MessageAbortedError'));}if(state.loseAbortReceipt)req.socket.destroy();else res.end('true');}
  else{res.statusCode=404;res.end('{}');}
 });await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port,http=new OpencodeHttp({url:'http://127.0.0.1:'+port,cwd,password:'p'.repeat(40),timeoutMs:1000}),binding={bindingId:'binding',profile:fence.profile,nativeId:'ses_owned',epoch:1,instance:'owner'},options={binding,providerId:'opencode',modelId:'big-pickle'};const drivers:OpencodeTurns[]=[];
 t.after(async()=>{state.healthGate?.open();state.submitGate?.open();state.abortGate?.open();for(const driver of drivers)driver.close();http.close();fence.close();await new Promise<void>(resolve=>server.close(()=>resolve()));rmSync(root,{recursive:true,force:true});});
 return {state,profile,root,http,fence,options,identity:{...binding,attemptId:'attempt',sourceDigest:hash('work')},driver(){const d=new OpencodeTurns(fence,http,options);drivers.push(d);return d;},row(){const db=new DatabaseSync(join(profile,'.durebak-opencode-turns.sqlite'));try{return db.prepare('SELECT * FROM turns WHERE attempt_id=?').get('attempt')!;}finally{db.close();}}};
}
function answer(parentID:string,error?:string,text='answer'):Message{return {info:{id:'msg_answer',sessionID:'ses_owned',role:'assistant',parentID,providerID:'opencode',modelID:'big-pickle',time:{created:1,completed:2},finish:'stop',...(error?{error:{name:error,data:{message:'PRIVATE'}}}:{})},parts:[{id:'part_answer',sessionID:'ses_owned',messageID:'msg_answer',type:'text',text}]};}
test('HTTP metadata is canonical, immutable and credential-free',async t=>{const f=await fixture(t);assert.deepEqual(Object.keys(f.http.metadata).sort(),['cwd','origin']);assert.equal(f.http.metadata.cwd,realpathSync.native(join(f.root,'input')));assert.ok(Object.isFrozen(f.http.metadata));assert.ok(!JSON.stringify(f.http.metadata).includes('pppp'));});
test('durable message identity precedes POST and ACK alone is not acceptance',async t=>{const f=await fixture(t),d=f.driver();f.state.beforePost=()=>{const row=f.row();assert.equal(row.state,'submitting');assert.match(row.message_id as string,/^msg_[A-Za-z0-9]+$/);assert.equal(row.source_digest,hash('work'));};const receipt=await d.submit(f.identity,'work');assert.equal(receipt.acknowledged,true);assert.equal(receipt.accepted,null);assert.equal(receipt.state,'unknown');assert.equal(f.state.posts,1);const observed=await d.observe(f.identity);assert.equal(observed.accepted,true);assert.equal(observed.state,'unknown');});
test('lost receipt survives live-owner reconnect without replaying submission',async t=>{const f=await fixture(t),d=f.driver();f.state.loseReceipt=true;assert.equal((await d.submit(f.identity,'work')).state,'unknown');const messageId=f.row().message_id as string;d.close();const reconnected=f.driver();await assert.rejects(reconnected.submit(f.identity,'work'),/submission_uncertain/);f.state.history.push(answer(messageId));assert.equal((await reconnected.observe(f.identity)).state,'succeeded');assert.equal(f.state.posts,1);assert.equal((await reconnected.readOutput(f.identity)).content,'answer');});
test('source and foreign owner mismatch refuse input before POST',async t=>{const f=await fixture(t),d=f.driver();await assert.rejects(d.submit(f.identity,'different'),/source_changed/);await assert.rejects(d.submit({...f.identity,instance:'foreign'},'work'),/driver_identity_mismatch/);assert.equal(f.state.posts,0);});
test('a prepared intent is saved before health awaits and cancellation prevents submission',async t=>{const f=await fixture(t),d=f.driver();f.state.healthGate=gate();const pending=d.submit(f.identity,'work');await new Promise(resolve=>setTimeout(resolve,25));assert.equal(f.row().state,'prepared');assert.equal((await d.interrupt(f.identity)).state,'not_accepted');f.state.healthGate.open();assert.equal((await pending).accepted,false);assert.equal(f.state.posts,0);assert.equal(f.state.aborts,0);});
test('delayed POST cancellation waits for exact running evidence before once-only abort',async t=>{const f=await fixture(t),d=f.driver();f.state.submitGate=gate();const pending=d.submit(f.identity,'work');await f.state.submitStarted.promise;assert.equal((await d.interrupt(f.identity)).state,'unknown');assert.equal(f.state.aborts,0);f.state.submitGate.open();await pending;assert.equal(f.state.aborts,0);f.state.history.push(running(f.row().message_id as string));assert.equal((await d.interrupt(f.identity)).state,'running');assert.equal(f.state.aborts,1);f.state.history=f.state.history.filter(m=>m.info.role==='user');f.state.history.push(answer(f.row().message_id as string,'MessageAbortedError'));assert.equal((await d.observe(f.identity)).state,'stopped');});
test('APIError with completed timestamp is durably failed without raw error output',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(answer(f.row().message_id as string,'APIError'));const result=await d.observe(f.identity);assert.equal(result.state,'failed');assert.equal(result.accepted,true);assert.ok(!JSON.stringify(result).includes('PRIVATE'));await assert.rejects(d.readOutput(f.identity),/native_output_unavailable/);});
test('foreign user text and model never supply accepted completion',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history[0]!.parts[0]!.text='foreign';f.state.history.push(answer(f.row().message_id as string));const result=await d.observe(f.identity);assert.equal(result.state,'unknown');assert.equal(result.accepted,null);await assert.rejects(d.readOutput(f.identity),/native_output_unavailable/);});
test('foreign history prevents model submission',async t=>{const f=await fixture(t),d=f.driver();f.state.history.push({info:{id:'msg_foreign',sessionID:'ses_owned',role:'user',model:{providerID:'opencode',modelID:'big-pickle'}},parts:[]});await assert.rejects(d.submit(f.identity,'work'),/host_unknown/);assert.equal(f.state.posts,0);});
test('one active intent is atomic across separate drivers sharing the live fence',async t=>{const f=await fixture(t),a=f.driver(),b=f.driver();f.state.healthGate=gate();const pending=a.submit(f.identity,'work');await new Promise(resolve=>setTimeout(resolve,20));await assert.rejects(b.submit({...f.identity,attemptId:'other'},'work'),/native_busy/);f.state.healthGate.open();await pending;assert.equal(f.state.posts,1);});
test('terminal output is immutable, paginated by UTF8 and bound to source and owner',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(answer(f.row().message_id as string,undefined,'한글 answer'));assert.equal((await d.observe(f.identity)).state,'succeeded');const first=await d.readOutput(f.identity,0,4);assert.equal(first.content,'한');assert.equal(first.digest,hash('한글 answer'));f.state.history=[];assert.equal((await d.readOutput(f.identity)).content,'한글 answer');assert.equal(statSync(join(f.profile,'.durebak-opencode-turns.sqlite')).mode&0o077,0);await assert.rejects(d.readOutput({...f.identity,sourceDigest:hash('other')}),/idempotency_conflict/);f.fence.close();await assert.rejects(d.readOutput(f.identity),/native_owner_closed/);});
test('unsafe ledger symlink cannot be adopted',async t=>{const f=await fixture(t);const outside=join(f.root,'outside');writeFileSync(outside,'private',{mode:0o600});symlinkSync(outside,join(f.profile,'.durebak-opencode-turns.sqlite'));assert.throws(()=>f.driver(),/native_ledger_unsafe/);});
test('foreign history appearing after acceptance fences whole-session abort',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');assert.equal((await d.observe(f.identity)).accepted,true);f.state.history.push({info:{id:'msg_foreign',sessionID:'ses_owned',role:'user',model:{providerID:'opencode',modelID:'big-pickle'}},parts:[]});assert.equal((await d.interrupt(f.identity)).state,'unknown');assert.equal(f.state.aborts,0);});
test('a completed attempt cannot abort the following continuation',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(answer(f.row().message_id as string));await d.observe(f.identity);const next={...f.identity,attemptId:'next',sourceDigest:hash('next work')};await d.submit(next,'next work');assert.equal((await d.interrupt(f.identity)).state,'succeeded');assert.equal(f.state.aborts,0);assert.equal(f.state.posts,2);});
test('a reopened ledger rejects a different model scope',async t=>{const f=await fixture(t),d=f.driver();d.close();assert.throws(()=>new OpencodeTurns(f.fence,f.http,{...f.options,modelId:'different'}),/native_ledger_invalid/);});
test('closing an observer driver does not cancel another drivers prepared work',async t=>{const f=await fixture(t),a=f.driver(),b=f.driver();f.state.healthGate=gate();const pending=a.submit(f.identity,'work');await new Promise(resolve=>setTimeout(resolve,20));b.close();assert.equal(f.row().state,'prepared');f.state.healthGate.open();await pending;assert.equal(f.state.posts,1);});

function running(parentID:string):Message{const message=answer(parentID);message.info.time={created:1};delete message.info.finish;message.parts=[];return message;}
test('204 and a stored user cannot spend abort before the native runner begins',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');await d.interrupt(f.identity);assert.equal(f.state.aborts,0);f.state.history.push(running(f.row().message_id as string));f.state.abortStops=true;assert.equal((await d.observe(f.identity)).state,'stopped');assert.equal(f.state.aborts,1);});
test('in-flight whole-session abort fences next input even after old completion',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(running(f.row().message_id as string));f.state.abortGate=gate();const cancel=d.interrupt(f.identity);await f.state.abortStarted.promise;try{f.state.history=f.state.history.filter(m=>m.info.role==='user');f.state.history.push(answer(f.row().message_id as string));assert.equal((await f.driver().observe(f.identity)).state,'succeeded');await assert.rejects(d.submit({...f.identity,attemptId:'next',sourceDigest:hash('next work')},'next work'),/native_abort_unresolved/);}finally{f.state.abortGate.open();await cancel;}assert.equal(f.state.posts,1);});
test('lost abort receipt retains the continuation fence across driver reconnect',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(running(f.row().message_id as string));f.state.loseAbortReceipt=true;await d.interrupt(f.identity);f.state.history=f.state.history.filter(m=>m.info.role==='user');f.state.history.push(answer(f.row().message_id as string));await d.observe(f.identity);d.close();const reconnected=f.driver();await assert.rejects(reconnected.submit({...f.identity,attemptId:'next',sourceDigest:hash('next work')},'next work'),/native_abort_unresolved/);assert.equal(f.state.posts,1);assert.equal(f.state.aborts,1);});
test('concurrent cancellation claims only one native abort',async t=>{const f=await fixture(t),a=f.driver(),b=f.driver();await a.submit(f.identity,'work');f.state.history.push(running(f.row().message_id as string));await Promise.all([a.interrupt(f.identity),b.interrupt(f.identity)]);assert.equal(f.state.aborts,1);assert.equal(f.row().abort_settled,1);});
test('cached output tampering is refused even under the same live owner',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history.push(answer(f.row().message_id as string));await d.observe(f.identity);const db=new DatabaseSync(join(f.profile,'.durebak-opencode-turns.sqlite'));db.prepare("UPDATE outputs SET text='changed' WHERE attempt_id='attempt'").run();db.close();await assert.rejects(d.readOutput(f.identity),/native_output_invalid/);});
test('foreign session metadata cannot authorize a model POST',async t=>{const f=await fixture(t),d=f.driver();f.state.foreignSession=true;await assert.rejects(d.submit(f.identity,'work'),/host_unknown/);assert.equal(f.row().state,'not_accepted');assert.equal(f.state.posts,0);});
test('exact input model mismatch cannot supply acceptance or completion',async t=>{const f=await fixture(t),d=f.driver();await d.submit(f.identity,'work');f.state.history[0]!.info.model={providerID:'opencode',modelID:'fallback'};assert.equal((await d.observe(f.identity)).accepted,null);await d.interrupt(f.identity);assert.equal(f.state.aborts,0);});
