import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {tmpdir} from 'node:os';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {join} from 'node:path';
import {OpencodeHttp} from '../src/opencode-http.js';
async function fixture(t:test.TestContext,handler:(req:IncomingMessage,res:ServerResponse)=>void,options:Record<string,number>={}){const server=createServer(handler),cwd=mkdtempSync(join(tmpdir(),'durebak-http-'));await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as {port:number};const client=new OpencodeHttp({url:`http://127.0.0.1:${address.port}`,password:'SYNTHETIC_PASSWORD_32_CHARACTERS_LONG',cwd,...options});t.after(()=>{client.close();server.closeAllConnections();server.close();rmSync(cwd,{recursive:true,force:true});});return {client,cwd,server};}
test('fixed routes use Basic auth and canonical directory without mutable query input',async t=>{let seen:IncomingMessage|undefined;const f=await fixture(t,(req,res)=>{seen=req;res.setHeader('content-type','application/json');res.end('[]');});assert.deepEqual(await f.client.call('messages',{nativeId:'ses_own'}),[]);const url=new URL(seen!.url!,'http://localhost');assert.equal(url.pathname,'/session/ses_own/message');assert.equal(url.searchParams.get('directory'),realpathSync.native(f.cwd));assert.match(seen!.headers.authorization!,/^Basic /);assert.ok(!JSON.stringify(f.client).includes('SYNTHETIC_PASSWORD'));await assert.rejects(f.client.call('messages',{nativeId:'ses_own',directory:'/foreign'}),/http_invalid_input/);});
test('async submission uses exact message identity and plain text body once',async t=>{let calls=0,body='';const f=await fixture(t,(req,res)=>{calls++;req.on('data',b=>body+=b);req.on('end',()=>{res.writeHead(204);res.end();});});assert.equal(await f.client.call('submit',{nativeId:'ses_own',messageId:'msg_once',providerId:'opencode',modelId:'big-pickle',text:'synthetic'}),null);const parsed=JSON.parse(body);assert.equal(parsed.messageID,'msg_once');assert.deepEqual(parsed.parts,[{type:'text',text:'synthetic'}]);assert.equal(parsed.system,undefined);assert.equal(calls,1);});
test('redirects and server error bodies are not followed or exposed',async t=>{for(const status of [302,401,500]){let calls=0;const f=await fixture(t,(_req,res)=>{calls++;res.writeHead(status,{location:'http://other.invalid'});res.end('SECRET_PROVIDER_CONTENT');});await assert.rejects(f.client.call('health'),e=>e instanceof Error&&e.message===`http_status:${status}`);assert.equal(calls,1);}});
test('response loss and timeout do not replay model submission',async t=>{for(const lose of [true,false]){let calls=0;const f=await fixture(t,(req,_res)=>{calls++;if(lose)req.socket.destroy();},{timeoutMs:25});await assert.rejects(f.client.call('submit',{nativeId:'ses_own',messageId:'msg_once',providerId:'opencode',modelId:'big-pickle',text:'synthetic'}),/http_transport_failed|http_timeout/);assert.equal(calls,1);}});
test('oversized content and invalid UTF8 or JSON are rejected without raw data',async t=>{for(const payload of [Buffer.alloc(100,65),Buffer.from([0xff]),Buffer.from('SECRET_INVALID_JSON')]){const f=await fixture(t,(_req,res)=>res.end(payload),{maxResponseBytes:64});await assert.rejects(f.client.call('health'),/http_response_size|http_protocol_error/);}});
test('pending limit and close abort outstanding reads and refuse later calls',async t=>{let calls=0;const f=await fixture(t,()=>{calls++;},{maxPending:1});const pending=f.client.call('health');await assert.rejects(f.client.call('health'),/http_pending_limit/);f.client.close();await assert.rejects(pending,/http_closed/);await assert.rejects(f.client.call('health'),/http_closed/);assert.ok(calls<=1);});
test('unowned origins and path traversal identifiers are rejected before network I/O',async t=>{const f=await fixture(t,(_req,res)=>res.end('{}'));for(const url of ['https://127.0.0.1:1234','http://localhost:1234','http://127.0.0.1:1234/path','http://127.0.0.1:1234?directory=foreign','http://user:pass@127.0.0.1:1234'])assert.throws(()=>new OpencodeHttp({url,cwd:f.cwd,password:'SYNTHETIC_PASSWORD_32_CHARACTERS_LONG'}),/http_invalid_origin/);await assert.rejects(f.client.call('session',{nativeId:'ses_../config'}),/http_invalid_input/);await assert.rejects(f.client.call('submit',{nativeId:'ses_owned',messageId:'msg_owned',providerId:'opencode',modelId:'big-pickle',text:'한'.repeat(6000)}),/http_invalid_input/);});
test('wrong success status cannot masquerade as an async submission receipt',async t=>{const f=await fixture(t,(_req,res)=>res.end('{}'));await assert.rejects(f.client.call('submit',{nativeId:'ses_own',messageId:'msg_once',providerId:'opencode',modelId:'big-pickle',text:'synthetic'}),/http_status:200/);});
test('prototype operation names never become HTTP routes',async t=>{let calls=0;const f=await fixture(t,(_req,res)=>{calls++;res.end('{}');});await assert.rejects(f.client.call('constructor' as never),/http_invalid_input/);assert.equal(calls,0);});
test('wall clock timeout limits a server that keeps trickling bytes',async t=>{const f=await fixture(t,(_req,res)=>{res.write('[');const timer=setInterval(()=>res.write(' '),5);res.on('close',()=>clearInterval(timer));},{timeoutMs:30});await assert.rejects(f.client.call('health'),/http_timeout/);});

test('session status uses only the fixed authenticated directory-scoped route',async t=>{let path='',directory='';const f=await fixture(t,(req,res)=>{const url=new URL(req.url!,'http://localhost');path=url.pathname;directory=url.searchParams.get('directory')!;res.end('{}');});assert.deepEqual(await f.client.call('statuses'),{});assert.equal(path,'/session/status');assert.equal(directory,realpathSync.native(f.cwd));});

test('owned creation fixes deny-all permissions and exact selected model without arbitrary overrides',async t=>{let calls=0,body='';const f=await fixture(t,(req,res)=>{calls++;req.on('data',chunk=>body+=chunk);req.on('end',()=>res.end('{"id":"ses_fresh"}'));});const input={title:'owned',providerId:'opencode',modelId:'big-pickle',ownerNonce:'owner-nonce'};assert.deepEqual(await f.client.call('createOwnedSession' as never,input),{id:'ses_fresh'});assert.deepEqual(JSON.parse(body),{title:'owned',agent:'build',model:{providerID:'opencode',id:'big-pickle'},permission:[{permission:'*',pattern:'*',action:'deny'}],metadata:{durebakOwner:'owner-nonce'}});for(const extra of [{permission:[]},{agent:'foreign'},{metadata:{}},{parentID:'ses_existing'},{workspaceID:'foreign'}])await assert.rejects(f.client.call('createOwnedSession' as never,{...input,...extra}),/http_invalid_input/);assert.equal(calls,1);});
