import test from 'node:test';
import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {startRuntime} from '../dist/runtime.js';
const exec=promisify(execFile),cli=resolve('dist/cli.js');
test('three-session operations survive restart, enforce queue states and preserve exported evidence',async()=>{
 const root=mkdtempSync(join(tmpdir(),'durebak-operations-')),data=join(root,'data');let runtime;
 const run=async(...args)=>JSON.parse((await exec(process.execPath,[cli,...args],{timeout:15000})).stdout);
 const rejectsWith=(promise,code)=>assert.rejects(promise,error=>{assert.equal(JSON.parse(error.stderr).error,code);return true;});
 const call=(session,op,args={})=>run('call',op,'--session',session.credential_file,'--json',JSON.stringify(args));
 try{
  runtime=await startRuntime(data);
  const sessions=[];
  for(const alias of ['writer','reviewer','verifier'])sessions.push(await run('register','--data-dir',data,'--workspace',root,'--alias',alias,'--harness','other'));
  const [writer,reviewer,verifier]=sessions;
  await call(reviewer,'session_state',{state:'busy'});
  const request={to:reviewer.session.id,body:'Review synthetic change',key:'review'};
  const sent=await call(writer,'send',request);
  assert.equal((await call(writer,'send',request)).id,sent.id);
  assert.equal((await call(reviewer,'receive')).items.length,0);
  const urgent=await call(writer,'send',{to:reviewer.session.id,body:'Synthetic urgent alert',key:'alert',priority:'urgent',urgentReason:'Operational scenario'});
  const urgentInbox=await call(reviewer,'receive');assert.equal(urgentInbox.items[0].id,urgent.id);
  await call(reviewer,'ack',{id:urgent.id,receipt:urgentInbox.items[0].receipt});
  await call(reviewer,'session_state',{state:'paused'});
  await runtime.close();runtime=undefined;
  await new Promise(r=>setTimeout(r,5100));
  runtime=await startRuntime(data);
  assert.equal((await run('doctor','--session',writer.credential_file)).ok,true);
  assert.equal((await call(reviewer,'receive')).items.length,0);
  await call(reviewer,'session_state',{state:'available'});
  const inbox=await call(reviewer,'receive');assert.equal(inbox.items.length,1);assert.equal(inbox.items[0].id,sent.id);
  await call(reviewer,'ack',{id:sent.id,receipt:inbox.items[0].receipt});
  assert.equal((await call(reviewer,'receive')).items.length,0);
  const task=await call(writer,'task_create',{title:'Synthetic fix',criteria:'Evidence retained after restart',key:'fix'});
  const claimed=await call(reviewer,'task_claim',{id:task.id,version:task.version});
  await rejectsWith(call(verifier,'task_claim',{id:task.id,version:task.version}),'claim_conflict');
  const artifact=await call(reviewer,'artifact_put',{content:'Synthetic verification evidence'});
  await rejectsWith(call(verifier,'task_complete',{id:task.id,version:claimed.version,hash:artifact.hash}),'claim_conflict');
  await call(reviewer,'task_complete',{id:task.id,version:claimed.version,hash:artifact.hash});
  const first=await run('export',task.id,'--session',writer.credential_file);
  assert.match(readFileSync(first.path,'utf8'),/State: completed/);
  assert.equal((await run('export',task.id,'--session',writer.credential_file)).status,'unchanged');
  writeFileSync(first.path,'Manual local note');
  await rejectsWith(run('export',task.id,'--session',writer.credential_file),'export_conflict');
  assert.equal(readFileSync(first.path,'utf8'),'Manual local note');
  await run('revoke',reviewer.session.id,'--data-dir',data);
  await rejectsWith(call(reviewer,'sessions'),'unauthorized');
  assert.equal((await call(verifier,'task_get',{id:task.id})).state,'completed');
 }finally{if(runtime)await runtime.close();rmSync(root,{recursive:true,force:true});}
});
