import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,type Socket} from 'node:net';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {OpencodeHttp} from '../src/opencode-http.js';
import {OwnedPeerConnector} from '../src/owned-peer-connector.js';
async function fixture(t:test.TestContext,verify:(tuple:{serverPort:number;clientPort:number})=>Promise<void>,options:{httpTimeout?:number;verifyTimeout?:number}={}){const cwd=mkdtempSync(join(tmpdir(),'durebak-peer-http-')),sockets=new Set<Socket>();let bytes=0,connections=0,connected:()=>void=()=>{};const server=createServer(socket=>{connections++;sockets.add(socket);connected();socket.on('close',()=>sockets.delete(socket));socket.on('data',chunk=>{bytes+=chunk.length;socket.end('HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}');});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port,connector=new OwnedPeerConnector({port,verify,assertLive:()=>{},timeoutMs:options.verifyTimeout??1000});const http=new OpencodeHttp({url:`http://127.0.0.1:${port}`,cwd,password:'SYNTHETIC_PASSWORD_32_CHARACTERS_LONG',timeoutMs:options.httpTimeout??1000},connector);t.after(async()=>{http.close();connector.close();for(const socket of sockets)socket.destroy();await new Promise<void>(resolve=>server.close(()=>resolve()));rmSync(cwd,{recursive:true,force:true});});return {http,connector,port,bytes:()=>bytes,connections:()=>connections,async connected(count=1){if(connections>=count)return;await new Promise<void>(resolve=>connected=()=>{if(connections>=count)resolve();});}};}
test('owned connection sends zero HTTP bytes until verification and uses that same socket afterward',async t=>{let allow:()=>void=()=>{},started:()=>void=()=>{},tuple:{serverPort:number;clientPort:number}|undefined;const pending=new Promise<void>(resolve=>allow=resolve),called=new Promise<void>(resolve=>started=resolve);const f=await fixture(t,async value=>{tuple=value;started();await pending;});const request=f.http.call('createOwnedSession',{title:'owned',providerId:'opencode',modelId:'big-pickle',ownerNonce:'nonce'});await called;await f.connected();assert.equal(f.bytes(),0);assert.equal(tuple!.serverPort,f.port);assert.ok(tuple!.clientPort>0);allow();assert.deepEqual(await request,{});assert.equal(f.connections(),1);assert.ok(f.bytes()>0);});
test('verification failure never discloses HTTP headers and never retries',async t=>{let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);const f=await fixture(t,async()=>{await gate;throw new Error('SECRET_NATIVE_REASON');});const request=f.http.call('health');await f.connected();release();await assert.rejects(request,e=>e instanceof Error&&e.message==='http_transport_failed');assert.equal(f.bytes(),0);assert.equal(f.connections(),1);});
for(const action of ['close','request-timeout','verify-timeout'])test(action+' destroys unverified socket before any delayed grant',async t=>{let allow:()=>void=()=>{};const gate=new Promise<void>(resolve=>allow=resolve);const f=await fixture(t,async()=>gate,{httpTimeout:action==='request-timeout'?50:1000,verifyTimeout:action==='verify-timeout'?50:1000});const request=f.http.call('health');await f.connected();if(action==='close')f.http.close();await assert.rejects(request,/http_closed|http_timeout|http_transport_failed/);allow();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.bytes(),0);assert.equal(f.connections(),1);});
test('every new connection verifies again rather than reusing old readiness',async t=>{let count=0;const f=await fixture(t,async()=>{count++;if(count===2)throw new Error('changed owner');});assert.deepEqual(await f.http.call('health'),{});const before=f.bytes();await assert.rejects(f.http.call('health'),/http_transport_failed/);assert.equal(count,2);await f.connected(2);assert.equal(f.connections(),2);assert.equal(f.bytes(),before);});
