import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {startRuntime} from '../src/runtime.js';
import {request,adminCall} from '../src/client.js';
import {z} from 'zod';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';

test('HTTP and real MCP share request ACL, delivery, completion and recovery checkpoint',async t=>{
 const root=mkdtempSync(join(tmpdir(),'durebak-request-http-'));const runtime=await startRuntime(root);
 const peers=await Promise.all(['a','b','c'].map(alias=>adminCall(root,'/v1/register',{workspace:'w',alias,provider:'codex'}) as Promise<{session:{id:string};token:string}>));
 const [a,b,c]=peers;if(!a||!b||!c)throw new Error('fixture');
 const http=async(token:string,operation:string,args:unknown={})=>await request(root,token,'/v1/session',{operation,args}) as any;
 const file=join(root,'worker.json');writeFileSync(file,JSON.stringify({data_dir:root,...b}),{mode:0o600});
 const mcp=new Client({name:'test',version:'1'});
 t.after(async()=>{await mcp.close();await runtime.close();rmSync(root,{recursive:true,force:true});});
 await mcp.connect(new StdioClientTransport({command:process.execPath,args:[resolve('dist/cli.js'),'mcp','--session',file],stderr:'pipe'}));
 const call=async(name:string,args:Record<string,unknown>)=>{const result=z.object({isError:z.boolean().optional(),content:z.array(z.object({text:z.string()})).min(1)}).parse(await mcp.callTool({name:`durebak_${name}`,arguments:args}));assert.equal(result.isError,undefined,JSON.stringify(result.content));return JSON.parse(result.content[0]!.text);};
 const input={to:b.session.id,body:'untrusted peer question',key:'q',priority:'urgent',urgentReason:'test immediate eligibility'};
 const preview=await http(a.token,'request_preview',{request:input});
 await assert.rejects(http(c.token,'request_preview_read',{id:preview.id}),/not_found/);
 assert.equal((await http(a.token,'request_preview_read',{id:preview.id})).content,input.body);
 const workerPreview=await call('request_preview',{request:{to:a.session.id,body:'worker preview',key:'preview'}});
 assert.equal((await call('request_preview_read',{id:workerPreview.id})).content,'worker preview');
 const q=await http(a.token,'request_create',{...input,previewId:preview.id});
 assert.equal((await call('request_messages',{id:q.id})).items.length,0);
 await assert.rejects(http(c.token,'request_get',{id:q.id}),/not_found/);
 const received=await call('receive',{});assert.equal(received.items[0].request_id,q.id);
 await call('ack',{id:received.items[0].id,receipt:received.items[0].receipt});
 await call('request_transition',{id:q.id,version:1,state:'accepted'});
 await call('request_message',{id:q.id,version:2,kind:'result',body:'answer',key:'result'});
 assert.equal((await http(a.token,'request_get',{id:q.id})).state,'completed');
 const cursor=(await call('inbox',{})).next;
 const cp=await call('checkpoint_set',{consumer:'worker',version:0,messageCursor:cursor,controlCursor:0});
 assert.equal((await http(b.token,'checkpoint_get',{consumer:'worker'})).version,cp.version);
 assert((await http(a.token,'runtime_info')).capabilities.includes('request_threads_v1'));
 const protectedInput={to:b.session.id,body:'protected question',key:'protected',priority:'urgent',urgentReason:'test immediate task',task:{title:'private task',criteria:'private criteria'}};
 const taskPreview=await http(a.token,'request_preview',{request:protectedInput});
 assert.equal((await http(a.token,'request_preview_read',{id:taskPreview.id,part:'criteria'})).content,'private criteria');
 const protectedRequest=await http(a.token,'request_create',{...protectedInput,previewId:taskPreview.id});
 await assert.rejects(http(c.token,'task_get',{id:protectedRequest.task.id}),/not_found/);
 await assert.rejects(http(b.token,'request_task_read',{id:protectedRequest.id}),/message_not_delivered/);
 const taskDelivery=await call('receive',{});await call('ack',{id:taskDelivery.items[0].id,receipt:taskDelivery.items[0].receipt});
 assert.equal((await call('request_task_read',{id:protectedRequest.id})).content,'private criteria');
 await assert.rejects(http(b.token,'task_claim',{id:protectedRequest.task.id,version:1}),/linked_request_operation_required/);
 await call('request_transition',{id:protectedRequest.id,version:1,state:'accepted',expectedTaskVersion:1});
 const artifact=await call('artifact_put',{content:'workspace-visible result'});
 await call('request_message',{id:protectedRequest.id,version:2,kind:'result',body:'protected result',key:'protected-result',expectedTaskVersion:2,hash:artifact.hash});
 assert.equal((await http(a.token,'request_get',{id:protectedRequest.id})).task.state,'completed');
 const upload=await http(a.token,'attachment_put',{name:'private.txt',content:'private attachment',key:'upload'});
 const attachmentInput={to:b.session.id,body:'attachment question',key:'attachment',priority:'urgent',urgentReason:'test attached delivery',uploads:[upload.id]};
 const attachmentPreview=await http(a.token,'request_preview',{request:attachmentInput});assert.equal(attachmentPreview.attachments[0].visibility,'request-private');
 const attachmentRequest=await http(a.token,'request_create',{...attachmentInput,previewId:attachmentPreview.id});
 assert.equal((await call('request_attachments',{id:attachmentRequest.id})).items.length,0);
 await assert.rejects(http(c.token,'artifact_read',{id:upload.hash}),/not_found/);
 await call('receive',{});const handles=await call('request_attachments',{id:attachmentRequest.id});
 assert.equal((await call('attachment_read',{id:handles.items[0].id})).content,'private attachment');
 await assert.rejects(http(c.token,'attachment_read',{id:handles.items[0].id}),/not_found/);
 const reviewRequest=await http(a.token,'request_create',{to:b.session.id,body:'revision question',task:protectedInput.task,key:'revision-review'});await new Promise(resolve=>setTimeout(resolve,5100));await call('receive',{});await call('request_transition',{id:reviewRequest.id,version:1,state:'accepted',expectedTaskVersion:1});
 const privateResult=await call('attachment_put',{name:'result',content:'private revision source',key:'revision-upload'});
 const revision=await call('request_revision',{id:reviewRequest.id,version:2,expectedTaskVersion:2,uploadId:privateResult.id,key:'revision'});
 assert.equal((await http(a.token,'request_bundle',{id:reviewRequest.id})).verification.status,'waiting_delivery');
 await new Promise(resolve=>setTimeout(resolve,5100));await http(a.token,'receive');assert.equal((await http(a.token,'request_revisions',{id:reviewRequest.id})).items[0].id,revision.id);
 const evidence=await http(a.token,'request_evidence',{id:reviewRequest.id,revisionId:revision.id,procedure:'npm test',result:'pass',attempt:'a1',key:'e1',startedAt:Date.now()-1000,endedAt:Date.now()});
 assert.equal((await call('request_verification',{id:reviewRequest.id})).status,'reported_pass');assert.equal((await call('request_evidence_read',{id:evidence.id})).content,'npm test');
 assert.equal((await call('request_evidence_list',{id:reviewRequest.id})).items[0].source,'self_reported');
 await call('request_message',{id:reviewRequest.id,version:2,expectedTaskVersion:3,hash:revision.hash,body:'done',kind:'result',key:'revision-result'});
 assert.equal((await http(a.token,'task_get',{id:reviewRequest.task.id})).result_hash,null);
 await assert.rejects(http(c.token,'request_verification',{id:reviewRequest.id}),/not_found/);
 assert((await call('runtime_info',{})).capabilities.includes('revision_verification_v1'));

 const dashboard=await call('collaboration_status',{});assert.equal(dashboard.mode,'cooperative');assert.ok(dashboard.requests.items.some((row:{id:string})=>row.id===reviewRequest.id));assert.ok(!JSON.stringify(dashboard).includes('private revision source'));
 const {promisify}=await import('node:util'),{execFile}=await import('node:child_process');const cli=await promisify(execFile)(process.execPath,[resolve('dist/cli.js'),'dashboard','--session',file],{timeout:10000});assert.ok(cli.stdout.includes('mode=cooperative'));assert.ok(cli.stdout.includes('host=unknown'));assert.ok(!cli.stdout.includes('private revision source'));

});
