import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {Store} from '../src/store.js';
import {WorkReservations} from '../src/work-reservations.js';
function fixture(t:test.TestContext){const dir=mkdtempSync(join(tmpdir(),'durebak-reserve-'));let now=100000;const clock={now:()=>now},store=new Store(dir,clock),db=new DatabaseSync(join(dir,'runtime.sqlite'));db.exec('PRAGMA foreign_keys=ON');t.after(()=>{db.close();store.close();rmSync(dir,{recursive:true,force:true});});const a=store.register('w','a','codex').session,b=store.register('w','b','codex').session;const binding=store.managedBind({sessionId:b.id,harness:'codex',profile:'isolated',nativeId:'thread',instance:'mock-owner',key:'binding'});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'on'});const q=store.requestCreate(a,{to:b.id,body:'exact question',key:'q',priority:'urgent',urgentReason:'test'});const owner={bindingId:binding.binding.id,epoch:1,instance:'mock-owner',ownerToken:binding.ownerToken!};const input={...owner,messageId:q.message_id,key:'reserve',driver:'read-only-mock' as const};return {dir,clock,store,db,a,b,q,owner,input,reservations:new WorkReservations(db,clock),advance:(ms:number)=>now+=ms};}
test('atomic reservation wins over cooperative receive without claiming delivery or native execution',t=>{
 const {store,db,b,q,input,reservations,dir,clock}=fixture(t),attempt=reservations.reserve(input);const competing=new Store(dir,clock);try{assert.equal(competing.receive(b).items.length,0);}finally{competing.close();}assert.equal(attempt.state,'reserved');assert.equal(attempt.native_verified,false);assert.equal(store.receive(b).items.length,0);assert.equal(db.prepare('SELECT delivered_at FROM messages WHERE id=?').get(q.message_id)!.delivered_at,null);assert.throws(()=>store.requestTaskRead(b,q.id),/message_not_delivered|not_found/);assert.equal(db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.spent_turns,1);assert.equal(reservations.reserve(input).id,attempt.id);
});
test('cooperative delivery wins first and no attempt or budget is committed',t=>{
 const {store,db,b,input,reservations}=fixture(t);store.receive(b);assert.throws(()=>reservations.reserve(input),/trigger_unavailable/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);assert.equal(db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.spent_turns,0);
});
test('reservation survives restart and expiry of ordinary queue lease cannot replay it',t=>{
 const {store,db,b,input,reservations,dir,clock,advance}=fixture(t),attempt=reservations.reserve(input);advance(31000);const reopenedDb=new DatabaseSync(join(dir,'runtime.sqlite'));try{const again=new WorkReservations(reopenedDb,clock);assert.equal(again.reserve(input).id,attempt.id);assert.throws(()=>again.reserve({...input,key:'second'}),/trigger_reserved/);}finally{reopenedDb.close();}assert.equal(store.receive(b).items.length,0);assert.equal(db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.spent_turns,1);
});
test('wrong owner secret, epoch, driver instance and unverified provider do not reserve work',t=>{
 const {db,input,reservations}=fixture(t);for(const [change,reason] of [[{ownerToken:'0'.repeat(64)},/unauthorized/],[{epoch:2},/owner_epoch_conflict/],[{instance:'other'},/owner_instance_conflict/],[{driver:'codex'},/driver_unverified/]] as const)assert.throws(()=>reservations.reserve({...input,...change} as typeof input),reason);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);
});
test('policy off, paused recipient, deadline and lease expiry block reservations',t=>{
 const {store,b,input,reservations,advance}=fixture(t);store.setSessionState(b,'paused');assert.throws(()=>reservations.reserve(input),/recipient_unavailable/);store.setSessionState(b,'available');store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});assert.throws(()=>reservations.reserve(input),/policy_off/);store.managedPolicy({bindingId:input.bindingId,version:3,enabled:true,key:'again'});advance(60000);assert.throws(()=>reservations.reserve(input),/execution_unknown/);advance(-60000);assert.throws(()=>reservations.reserve(input),/execution_unknown/);
});
test('source and policy are revalidated immediately before durable submission',t=>{
 const {store,db,a,q,input,reservations}=fixture(t),attempt=reservations.reserve(input);store.requestTransition(a,q.id,1,'cancelled');assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/trigger_unavailable|request_closed/);assert.equal(db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');
});
test('changed input or grant prevents submission; successful submitting is one-way',t=>{
 const {db,input,reservations}=fixture(t),attempt=reservations.reserve(input);db.prepare('UPDATE messages SET body=? WHERE id=?').run('changed',input.messageId);assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/source_changed/);db.prepare('UPDATE messages SET body=? WHERE id=?').run('exact question',input.messageId);const result=reservations.submitting({...input,attemptId:attempt.id});assert.equal(result.state,'submitting');assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/submission_uncertain/);
});
test('turn budget and native binding concurrency are charged atomically',t=>{
 const {store,db,a,b,input,reservations}=fixture(t);db.prepare('UPDATE managed_policies SET spent_turns=30 WHERE binding_id=?').run(input.bindingId);assert.throws(()=>reservations.reserve(input),/turn_budget_exhausted/);db.prepare('UPDATE managed_policies SET spent_turns=0 WHERE binding_id=?').run(input.bindingId);reservations.reserve(input);const q2=store.requestCreate(a,{to:b.id,body:'second',key:'q2',priority:'urgent',urgentReason:'test'});assert.throws(()=>reservations.reserve({...input,messageId:q2.message_id,key:'q2'}),/native_busy/);assert.equal(db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.spent_turns,1);
});
test('storage failure rolls back the attempt, prefix locks and charged budgets',t=>{
 const {db,store,b,input,reservations}=fixture(t);db.exec("CREATE TRIGGER fail_reservation BEFORE INSERT ON work_reservations BEGIN SELECT RAISE(ABORT,'injected_storage_failure'); END");assert.throws(()=>reservations.reserve(input),/injected_storage_failure/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);assert.equal(db.prepare('SELECT count(*) n FROM work_scopes').get()!.n,0);assert.equal(db.prepare('SELECT spent_turns FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.spent_turns,0);assert.equal(store.receive(b).items.length,1);
});
test('a completed result never creates execution intent for a creator that was not waiting',t=>{
 const {store,db,a,b,q,input,reservations,advance}=fixture(t);store.receive(b);store.requestTransition(b,q.id,1,'accepted');const artifact=store.putArtifact(b,'result'),result=store.requestMessage(b,{id:q.id,version:2,kind:'result',body:'done',hash:artifact.hash,key:'result'});advance(5000);const binding=store.managedBind({sessionId:a.id,harness:'codex',profile:'isolated',nativeId:'creator',instance:'mock-owner',key:'creator'});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'creator-on'});assert.throws(()=>reservations.reserve({...input,bindingId:binding.binding.id,ownerToken:binding.ownerToken!,messageId:result.id,key:'result'}),/continuation_waiter_missing/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);assert.equal(store.receive(a).items.length,1);
});

test('policy version changes and duplicate keys cannot authorize a different submission',t=>{
 const {store,db,input,reservations}=fixture(t),attempt=reservations.reserve(input);assert.throws(()=>reservations.reserve({...input,messageId:'different'}),/idempotency_conflict/);store.managedPolicy({bindingId:input.bindingId,version:2,enabled:false,key:'off'});assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/policy_off/);store.managedPolicy({bindingId:input.bindingId,version:3,enabled:true,key:'on-again'});assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/policy_changed/);assert.equal(db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');
});
test('workspace concurrency allows three distinct native owners and blocks the fourth',t=>{
 const {store,db,a,input,reservations}=fixture(t);for(let i=0;i<4;i++){const session=store.register('w','worker'+i,'codex').session,binding=store.managedBind({sessionId:session.id,harness:'codex',profile:'isolated',nativeId:'thread'+i,instance:'mock-owner',key:'binding'+i});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'on'+i});const q=store.requestCreate(a,{to:session.id,body:'question',key:'q'+i});db.prepare('UPDATE messages SET due_at=100000 WHERE id=?').run(q.message_id);const candidate={...input,bindingId:binding.binding.id,ownerToken:binding.ownerToken!,messageId:q.message_id,key:'reserve'+i};if(i<3)reservations.reserve(candidate);else assert.throws(()=>reservations.reserve(candidate),/workspace_busy/);}assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,3);
});
test('revoked owner and missing source refuse work without charging any turn',t=>{
 const {store,db,b,input,reservations}=fixture(t);db.prepare('UPDATE messages SET body=? WHERE id=?').run('x'.repeat(16384),input.messageId);assert.throws(()=>reservations.reserve(input),/context_unavailable/);store.revoke(b.id);assert.throws(()=>reservations.reserve(input),/binding_revoked/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);
});

test('deadline and message TTL prevent a new reservation and never spend a turn',t=>{
 const {db,input,reservations,advance}=fixture(t);db.prepare('UPDATE requests SET deadline_at=100001 WHERE message_id=?').run(input.messageId);advance(1);assert.throws(()=>reservations.reserve(input),/request_closed/);db.prepare('UPDATE requests SET deadline_at=700000 WHERE message_id=?').run(input.messageId);db.prepare('UPDATE messages SET expires_at=100001 WHERE id=?').run(input.messageId);assert.throws(()=>reservations.reserve(input),/trigger_expired/);assert.equal(db.prepare('SELECT count(*) n FROM work_attempts').get()!.n,0);
});
test('continuation cannot create a fresh root budget after cooperative work',t=>{
 const {store,a,b,q,input,reservations,advance}=fixture(t);store.receive(b);store.requestTransition(b,q.id,1,'accepted');const answer=store.requestMessage(b,{id:q.id,version:2,kind:'answer',body:'answer',key:'answer'});advance(5000);const binding=store.managedBind({sessionId:a.id,harness:'codex',profile:'isolated',nativeId:'creator',instance:'mock-owner',key:'creator'});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'creator-on'});assert.throws(()=>reservations.reserve({...input,bindingId:binding.binding.id,ownerToken:binding.ownerToken!,messageId:answer.id,key:'answer'}),/continuation_waiter_missing/);
});
test('failed durable submitting write leaves work reserved and cannot authorize a driver call',t=>{
 const {db,input,reservations}=fixture(t),attempt=reservations.reserve(input);db.exec("CREATE TRIGGER fail_submission BEFORE UPDATE OF state ON work_attempts BEGIN SELECT RAISE(ABORT,'injected_submission_failure'); END");assert.throws(()=>reservations.submitting({...input,attemptId:attempt.id}),/injected_submission_failure/);assert.equal(db.prepare('SELECT state FROM work_attempts WHERE id=?').get(attempt.id)!.state,'reserved');
});

test('observing an expired root grant is durable even when continuation reservation is rejected',t=>{
 const {store,db,a,b,q,input,reservations,advance}=fixture(t);store.receive(b);store.requestTransition(b,q.id,1,'accepted');const answer=store.requestMessage(b,{id:q.id,version:2,kind:'answer',body:'answer',key:'answer'});const binding=store.managedBind({sessionId:a.id,harness:'codex',profile:'isolated',nativeId:'creator',instance:'mock-owner',key:'creator'});store.managedPolicy({bindingId:binding.binding.id,version:1,enabled:true,key:'creator-on'});db.prepare('UPDATE managed_policies SET expires_at=101000 WHERE binding_id=?').run(input.bindingId);db.prepare('INSERT INTO work_scopes(request_id,scope_id,owner_binding,max_turns,max_concurrent,expires_at) VALUES(?,?,?,30,3,101000)').run(q.id,'seed-root',input.bindingId);advance(5000);assert.throws(()=>reservations.reserve({...input,bindingId:binding.binding.id,ownerToken:binding.ownerToken!,messageId:answer.id,key:'answer'}),/continuation_waiter_missing/);assert.equal(db.prepare('SELECT expired FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.expired,1);
});

test('separate requests share the persistent grant scope and exhausted aggregate budget',t=>{
 const {store,db,a,b,input,reservations}=fixture(t),first=reservations.reserve(input);assert.equal(db.prepare('SELECT scope_id FROM work_scopes').get()!.scope_id,db.prepare('SELECT scope_id FROM managed_policies WHERE binding_id=?').get(input.bindingId)!.scope_id);db.prepare("UPDATE work_attempts SET state='completed' WHERE id=?").run(first.id);db.prepare('DELETE FROM work_reservations WHERE attempt_id=?').run(first.id);db.prepare('UPDATE managed_policies SET active_turns=0,spent_turns=30 WHERE binding_id=?').run(input.bindingId);db.prepare('UPDATE work_scopes SET active_turns=0 WHERE request_id=?').run(first.request_id);const q2=store.requestCreate(a,{to:b.id,body:'question',key:'second',priority:'urgent',urgentReason:'test'});assert.throws(()=>reservations.reserve({...input,messageId:q2.message_id,key:'second'}),/turn_budget_exhausted/);assert.equal(db.prepare('SELECT count(*) n FROM work_scopes').get()!.n,1);
});
