import {DatabaseSync} from 'node:sqlite';
import {closeSync,constants,lstatSync,openSync,realpathSync} from 'node:fs';
import {join} from 'node:path';
import {z} from 'zod';
import {CodexRpc} from './codex-rpc.js';
import {NativeProfileFence} from './native-profile-fence.js';
import {fail,hash,short} from './domain.js';
import {transaction} from './transactions.js';
import {range} from './content.js';
const bindingSchema=z.object({bindingId:short,epoch:z.number().int().positive(),instance:short,profile:short,nativeId:short}).strict();
const identitySchema=bindingSchema.extend({attemptId:short,sourceDigest:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
type Binding=z.infer<typeof bindingSchema>;type Identity=z.infer<typeof identitySchema>;
interface Options {binding:Binding;cwd:string;permissionProfile:string}
const turnSchema=z.object({id:short,status:z.enum(['inProgress','completed','failed','interrupted']),items:z.array(z.unknown())});
type NativeTurn=z.infer<typeof turnSchema>;
interface Intent {attempt_id:string;source_digest:string;native_id:string;turn_id:string|null;accepted:number;state:'prepared'|'submitting'|'running'|'unknown'|'succeeded'|'failed'|'stopped'|'not_accepted';stop_requested:number;interrupt_claimed:number}
const terminal=(state:string)=>['succeeded','failed','stopped','not_accepted'].includes(state);
// Internal native protocol/intent layer only. It has no controller authority.
// A caller must own the host and verify its scope before offering model input.
// Health proves contact/auth presence, never entitlement or tool isolation.
export class CodexTurns {
 private db:DatabaseSync;private ownerId:string;private closed=false;private submissions=new Set<string>();private binding:Binding;private cwd:string;private permissionProfile:string;
 constructor(private fence:NativeProfileFence,private rpc:CodexRpc,options:Options){
  this.binding=bindingSchema.parse(options.binding);this.cwd=realpathSync.native(options.cwd);this.permissionProfile=short.parse(options.permissionProfile);const owner=fence.status();this.ownerId=owner.id;this.assertOwner();
  const file=join(fence.profile,'.durebak-turns.sqlite');let fresh=false;try{const fd=openSync(file,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);closeSync(fd);fresh=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='EEXIST')fail('native_ledger_unavailable');const stat=lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||(stat.mode&0o077)!==0||stat.uid!==process.getuid?.())fail('native_ledger_unsafe');}
  this.db=new DatabaseSync(file);const scope=hash(JSON.stringify({owner:this.ownerId,binding:this.binding,cwd:this.cwd,permissions:this.permissionProfile}));try{
   if(fresh){this.db.exec("PRAGMA synchronous=FULL; PRAGMA journal_mode=DELETE; CREATE TABLE scope(digest TEXT NOT NULL) STRICT; CREATE TABLE turns(attempt_id TEXT PRIMARY KEY,source_digest TEXT NOT NULL,native_id TEXT NOT NULL,turn_id TEXT UNIQUE,accepted INTEGER NOT NULL DEFAULT 0,state TEXT NOT NULL CHECK(state IN ('prepared','submitting','running','unknown','succeeded','failed','stopped','not_accepted')),stop_requested INTEGER NOT NULL DEFAULT 0,interrupt_claimed INTEGER NOT NULL DEFAULT 0) STRICT; CREATE UNIQUE INDEX single_active_turn ON turns((1)) WHERE state IN ('prepared','submitting','running','unknown'); PRAGMA user_version=1;");this.db.prepare('INSERT INTO scope VALUES(?)').run(scope);}
   const rows=this.db.prepare('SELECT digest FROM scope').all();const version=(this.db.prepare('PRAGMA user_version').get() as {user_version:number}).user_version;if(![1,2].includes(version)||rows.length!==1||rows[0]?.digest!==scope)fail('native_ledger_scope_conflict');if(version===1)transaction(this.db,()=>{this.db.exec("CREATE TABLE IF NOT EXISTS turn_outputs(attempt_id TEXT PRIMARY KEY,item_id TEXT NOT NULL,phase TEXT NOT NULL CHECK(phase IN ('final_answer','unknown')),text TEXT NOT NULL CHECK(length(CAST(text AS BLOB)) BETWEEN 1 AND 65536),digest TEXT NOT NULL CHECK(length(digest)=64)) STRICT; PRAGMA user_version=2;");});this.db.prepare('SELECT attempt_id,item_id,phase,text,digest FROM turn_outputs LIMIT 0').all();
  }catch{this.db.close();fail('native_ledger_invalid');}
 }
 private assertOwner(){if(this.closed)fail('native_driver_closed');const owner=this.fence.status();if(owner.id!==this.ownerId||owner.state!=='owned'||owner.epoch!==this.binding.epoch||owner.instance!==this.binding.instance||owner.native_id!==this.binding.nativeId||this.fence.profile!==this.binding.profile)fail('driver_identity_mismatch');}
 private identity(raw:Identity){const id=identitySchema.parse(raw);this.assertOwner();for(const key of ['bindingId','epoch','instance','profile','nativeId'] as const)if(id[key]!==this.binding[key])fail('driver_identity_mismatch');return id;}
 private row(id:Identity){const row=this.db.prepare('SELECT * FROM turns WHERE attempt_id=?').get(id.attemptId) as unknown as Intent|undefined;if(!row)fail('native_intent_missing');if(row.native_id!==id.nativeId||row.source_digest!==id.sourceDigest)fail('idempotency_conflict');return row;}
 private outcome(id:Identity,row:Intent){return {attemptId:id.attemptId,epoch:id.epoch,instance:id.instance,sourceDigest:id.sourceDigest,turnId:row.turn_id,accepted:row.accepted?true:row.state==='not_accepted'?false:null,state:['prepared','submitting'].includes(row.state)?'unknown' as const:row.state};}
 private unknown(id:Identity){this.assertOwner();this.db.prepare("UPDATE turns SET state='unknown' WHERE attempt_id=? AND state IN ('submitting','running','unknown')").run(id.attemptId);return this.outcome(id,this.row(id));}
 private async thread(includeTurns=false){const result=z.object({thread:z.object({id:short,cliVersion:z.literal('0.146.0'),cwd:z.string(),modelProvider:z.literal('openai'),status:z.object({type:z.enum(['idle','active','notLoaded','systemError'])}),turns:z.array(turnSchema).max(1000)})}).parse(await this.rpc.call('thread/read',{threadId:this.binding.nativeId,includeTurns}));this.assertOwner();if(result.thread.id!==this.binding.nativeId||realpathSync.native(result.thread.cwd)!==this.cwd)fail('native_thread_conflict');return result.thread;}
 async health(){return this.readiness();}
 private async readiness(ignoreAttempt:string|null=null){this.assertOwner();try{const thread=await this.thread(),account=z.object({requiresOpenaiAuth:z.literal(true),account:z.object({type:z.enum(['chatgpt','apiKey'])}).nullable()}).parse(await this.rpc.call('account/read',{refreshToken:false}));this.assertOwner();const auth=account.account?'present' as const:'required' as const;const active=this.db.prepare("SELECT attempt_id FROM turns WHERE state IN ('prepared','submitting','running','unknown') AND (? IS NULL OR attempt_id<>?)").get(ignoreAttempt,ignoreAttempt);return {readiness:thread.status.type==='active'||active?'busy' as const:thread.status.type==='idle'&&auth==='present'?'ready' as const:'unknown' as const,auth,entitlement:'unverified' as const};}catch{this.assertOwner();return {readiness:'unknown' as const,auth:'unknown' as const,entitlement:'unverified' as const};}}
 async submit(raw:Identity,source:string){const id=this.identity(raw);if(typeof source!=='string'||Buffer.byteLength(source)>16384||hash(source)!==id.sourceDigest)fail('source_changed');
  transaction(this.db,()=>{if(this.db.prepare('SELECT attempt_id FROM turns WHERE attempt_id=?').get(id.attemptId))fail('submission_uncertain');if(this.db.prepare("SELECT attempt_id FROM turns WHERE state IN ('prepared','submitting','running','unknown')").get())fail('native_busy');if((this.db.prepare('SELECT count(*) n FROM turns').get() as {n:number}).n>=30)fail('native_turn_limit');this.db.prepare("INSERT INTO turns(attempt_id,source_digest,native_id,state) VALUES(?,?,?,'prepared')").run(id.attemptId,id.sourceDigest,id.nativeId);});
  this.submissions.add(id.attemptId);
  const health=await this.readiness(id.attemptId);this.assertOwner();if(this.row(id).state==='not_accepted')return this.outcome(id,this.row(id));if(health.readiness!=='ready'){this.db.prepare("UPDATE turns SET state='not_accepted' WHERE attempt_id=? AND state='prepared'").run(id.attemptId);fail(health.readiness==='busy'?'host_busy':health.auth==='required'?'native_auth_required':'host_unknown');}
  if(this.db.prepare("UPDATE turns SET state='submitting' WHERE attempt_id=? AND state='prepared' AND stop_requested=0").run(id.attemptId).changes!==1)return this.outcome(id,this.row(id));
  try{const result=z.object({turn:turnSchema}).parse(await this.rpc.call('turn/start',{threadId:id.nativeId,cwd:this.cwd,permissions:this.permissionProfile,approvalPolicy:'never',input:[{type:'text',text:source}]}));this.assertOwner();if(this.db.prepare('SELECT attempt_id FROM turns WHERE turn_id=?').get(result.turn.id))return this.unknown(id);this.db.prepare('UPDATE turns SET turn_id=?,accepted=1 WHERE attempt_id=?').run(result.turn.id,id.attemptId);const outcome=this.save(id,result.turn);return this.row(id).stop_requested&&!terminal(outcome.state)?this.interrupt(id):outcome;}catch{this.assertOwner();return this.unknown(id);}
 }
 private save(id:Identity,turn:NativeTurn){this.assertOwner();const row=this.row(id);if(terminal(row.state))return this.outcome(id,row);if(row.turn_id!==turn.id)fail('native_turn_conflict');const state=turn.status==='completed'?'succeeded':turn.status==='failed'?'failed':turn.status==='interrupted'?'stopped':row.stop_requested?'unknown':'running';this.db.prepare('UPDATE turns SET state=? WHERE attempt_id=?').run(state,id.attemptId);return this.outcome(id,this.row(id));}
 async observe(raw:Identity){const id=this.identity(raw),row=this.row(id);if(terminal(row.state))return this.outcome(id,row);if(!row.turn_id)return this.unknown(id);try{const thread=await this.thread(true),matches=thread.turns.filter(t=>t.id===row.turn_id);if(matches.length!==1)return this.unknown(id);return this.save(id,matches[0]!);}catch{this.assertOwner();return this.unknown(id);}}
 // A successful host turn is not request completion or verification. Freeze only
 // its selected answer; never expose reasoning, tool output or adjacent turns.
 async readOutput(raw:Identity,offset=0,limit=4096){const id=this.identity(raw);z.number().int().min(0).max(65536).parse(offset);z.number().int().min(4).max(4096).parse(limit);const intent=this.row(id);if(!intent.turn_id||!intent.accepted||['failed','stopped','not_accepted','prepared','submitting'].includes(intent.state))fail('native_output_unavailable');
  const snapshotSchema=z.object({item_id:short,phase:z.enum(['final_answer','unknown']),text:z.string(),digest:z.string().regex(/^[a-f0-9]{64}$/)});const cached=()=>this.db.prepare('SELECT item_id,phase,text,digest FROM turn_outputs WHERE attempt_id=?').get(id.attemptId);let snapshot=cached();
  if(!snapshot){const thread=await this.thread(true),matches=thread.turns.filter(turn=>turn.id===intent.turn_id);if(matches.length!==1||matches[0]!.status!=='completed')fail('native_output_not_ready');const turn=matches[0]!,messages=turn.items.filter(item=>item&&typeof item==='object'&&'type' in item&&item.type==='agentMessage').map(item=>z.object({id:short,text:z.string(),phase:z.enum(['commentary','final_answer']).nullable().optional()}).parse(item));if(new Set(messages.map(m=>m.id)).size!==messages.length)fail('native_output_ambiguous');const finals=messages.filter(m=>m.phase==='final_answer'),unknowns=messages.filter(m=>m.phase==null),selected=finals.length?finals:unknowns;if(selected.length!==1)fail('native_output_ambiguous');const answer=selected[0]!,bytes=Buffer.byteLength(answer.text);if(!bytes||bytes>65536)fail('native_output_size');const digest=hash(answer.text),phase=answer.phase==='final_answer'?'final_answer':'unknown';
   transaction(this.db,()=>{this.assertOwner();const outcome=this.save(id,turn);if(outcome.state!=='succeeded')fail('native_output_unavailable');const existing=cached();if(existing){if(existing.digest!==digest||existing.item_id!==answer.id||existing.phase!==phase)fail('native_output_changed');}else this.db.prepare('INSERT INTO turn_outputs VALUES(?,?,?,?,?)').run(id.attemptId,answer.id,phase,answer.text,digest);});snapshot=cached();
  }
  this.assertOwner();const result=snapshotSchema.parse(snapshot);if(this.row(id).state!=='succeeded'||hash(result.text)!==result.digest||!Buffer.byteLength(result.text)||Buffer.byteLength(result.text)>65536)fail('native_output_invalid');return {...this.outcome(id,this.row(id)),itemId:result.item_id,phase:result.phase,digest:result.digest,...range(result.text,offset,limit)};
 }
 async interrupt(raw:Identity){const id=this.identity(raw),row=this.row(id);if(terminal(row.state))return this.outcome(id,row);if(row.state==='prepared'){this.db.prepare("UPDATE turns SET state='not_accepted',stop_requested=1 WHERE attempt_id=? AND state='prepared'").run(id.attemptId);return this.outcome(id,this.row(id));}this.db.prepare('UPDATE turns SET stop_requested=1 WHERE attempt_id=?').run(id.attemptId);if(!row.turn_id)return this.unknown(id);if(this.db.prepare('UPDATE turns SET interrupt_claimed=1 WHERE attempt_id=? AND interrupt_claimed=0').run(id.attemptId).changes!==1)return this.observe(id);try{await this.rpc.call('turn/interrupt',{threadId:id.nativeId,turnId:row.turn_id});this.assertOwner();return this.observe(id);}catch{this.assertOwner();return this.unknown(id);}}
 close(){if(this.closed)return;this.closed=true;try{transaction(this.db,()=>{for(const attempt of this.submissions){this.db.prepare("UPDATE turns SET state='not_accepted' WHERE attempt_id=? AND state='prepared'").run(attempt);this.db.prepare("UPDATE turns SET state='unknown' WHERE attempt_id=? AND state IN ('submitting','running')").run(attempt);}});}finally{this.db.close();}}
}
