import {spawn,execFile,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {promisify} from 'node:util';
import {existsSync,lstatSync,readFileSync,realpathSync,readdirSync,writeFileSync,symlinkSync,unlinkSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {fail,short} from './domain.js';
import {CodexRpc} from './codex-rpc.js';
import {CodexTurns} from './codex-turns.js';
import {NativeProfileFence} from './native-profile-fence.js';
const exec=promisify(execFile),permissionProfile='durebak-scoped';
const optionsSchema=z.object({binary:z.string().min(1),profile:z.string().min(1),cwd:z.string().min(1),instance:short,timeoutMs:z.number().int().min(10).max(20000).default(20000),shutdownMs:z.number().int().min(10).max(3000).default(1000)}).strict();
export type OwnedCodexOptions=z.input<typeof optionsSchema>;
function privateDir(path:string){const normalized=path.replace(/\/+$/,'')||'/',stat=lstatSync(normalized);if(stat.isSymbolicLink()||!stat.isDirectory()||(stat.mode&0o077)!==0||stat.uid!==process.getuid?.())fail('native_directory_unsafe');return realpathSync.native(normalized);}
function configText(cwd:string){return `approval_policy = "never"\ndefault_permissions = "${permissionProfile}"\n[permissions.${permissionProfile}.filesystem]\n":minimal" = "read"\n${JSON.stringify(cwd)} = "read"\n[permissions.${permissionProfile}.network]\nenabled = false\n`;}
async function within(promise:Promise<void>,ms:number){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('native_shutdown_timeout')),ms);})]);}finally{if(timer)clearTimeout(timer);}}
function verifyConfig(raw:unknown,cwd:string){const config=z.object({config:z.object({approval_policy:z.literal('never'),default_permissions:z.literal(permissionProfile),mcp_servers:z.record(z.string(),z.unknown()),model_providers:z.record(z.string(),z.unknown()),model_provider:z.literal('openai').nullable(),sandbox_mode:z.null(),permissions:z.record(z.string(),z.unknown())})}).parse(raw).config;
 const selected=z.object({extends:z.null().optional(),filesystem:z.record(z.string(),z.unknown()),network:z.object({enabled:z.literal(false)})}).parse(config.permissions[permissionProfile]);const entries=Object.entries(selected.filesystem).filter(([k,v])=>k!=='glob_scan_max_depth'||v!==null);if(Object.keys(config.mcp_servers).length||Object.keys(config.model_providers).length||entries.length!==2||selected.filesystem[':minimal']!=='read'||selected.filesystem[cwd]!=='read')fail('native_effective_config_conflict');}
async function verifyCommands(rpc:CodexRpc,profile:string,cwd:string){const suffix=randomUUID(),token='DUREBAK_CANARY_'+suffix,root=mkdtempSync(join(tmpdir(),'durebak-host-canary-')),allowed=join(cwd,'.durebak-read-'+suffix),outside=join(root,'outside'),privateFile=join(profile,'.durebak-canary-'+suffix),link=join(cwd,'.durebak-symlink-'+suffix),written=join(cwd,'.durebak-write-'+suffix);const owned:string[]=[];
 try{for(const file of [allowed,outside,privateFile]){writeFileSync(file,token,{mode:0o600,flag:'wx'});owned.push(file);}symlinkSync(outside,link);owned.push(link);const run=async(command:string[])=>z.object({stdout:z.string(),exitCode:z.number().int()}).parse(await rpc.call('command/exec',{command,cwd,permissionProfile,timeoutMs:5000}));const read=await run(['/bin/cat',allowed]);if(read.exitCode!==0||read.stdout!==token)fail('native_read_scope_unverified');for(const file of [outside,privateFile,link])if((await run(['/bin/cat',file])).exitCode===0)fail('native_read_scope_unverified');const write=await run(['/usr/bin/touch',written]);if(write.exitCode===0||existsSync(written))fail('native_write_scope_unverified');
 }finally{for(const file of owned.reverse())unlinkSync(file);if(existsSync(written))unlinkSync(written);rmSync(root,{recursive:true,force:true});}}
// Only fresh owned hosts are created. This non-model factory verifies command
// canaries, not all model tool paths, and confers no controller authority.
export async function startOwnedCodexHost(input:OwnedCodexOptions){
 const options=optionsSchema.parse(input);if(!['darwin','linux'].includes(process.platform))fail('native_platform_unsupported');const cwd=privateDir(options.cwd),profile=privateDir(options.profile),binary=realpathSync.native(options.binary);if(!lstatSync(binary).isFile()||readdirSync(cwd).length)fail('native_input_not_empty');const configFile=join(profile,'config.toml'),stat=lstatSync(configFile);if(stat.isSymbolicLink()||!stat.isFile()||stat.nlink!==1||(stat.mode&0o077)!==0||stat.uid!==process.getuid?.())fail('native_profile_config_unsafe');if(readFileSync(configFile,'utf8')!==configText(cwd))fail('native_profile_config_mismatch');
 const fence=NativeProfileFence.claim(profile,options.instance),env={PATH:process.env.PATH??'',...(process.env.HOME?{HOME:process.env.HOME}:{}),CODEX_HOME:profile};let child:ChildProcessWithoutNullStreams|undefined,rpc:CodexRpc|undefined,turns:CodexTurns|undefined,bindingId:string|undefined,closed=false,released=false,cleanupFailed=false,exited:Promise<void>|undefined,closing:Promise<void>|undefined;
 const retire=()=>{if(closed)return;closed=true;try{rpc?.close();}catch{cleanupFailed=true;}try{turns?.close();}catch{cleanupFailed=true;}};
 const release=()=>{if(released)return;try{fence.close();released=true;}catch{cleanupFailed=true;}};
 const signal=(name:NodeJS.Signals)=>{if(!child?.pid)return;try{process.kill(-child.pid,name);}catch(error){if(!['ESRCH','EPERM'].includes((error as NodeJS.ErrnoException).code??''))throw error;}};
 const groupGone=()=>{if(!child?.pid)return true;try{process.kill(-child.pid,0);return false;}catch(error){if((error as NodeJS.ErrnoException).code==='ESRCH')return true;if((error as NodeJS.ErrnoException).code==='EPERM')return false;throw error;}};
 const waitForExit=async()=>{const deadline=Date.now()+options.shutdownMs;while(!groupGone()){if(Date.now()>=deadline)fail('native_shutdown_timeout');await new Promise(resolve=>setTimeout(resolve,10));}if(exited)await within(exited,Math.max(1,deadline-Date.now()));};
 // EPERM can occur during macOS zombie reaping; it remains pending, never gone.
 // Leader exit is insufficient: descendants may close their pipes and ignore TERM.
 // Keep the ownership fence until both the leader and its owned group are gone.
 const close=()=>{if(closing)return closing;closing=(async()=>{retire();if(!released){if(child&&exited){child.stdin.end();signal('SIGTERM');try{await waitForExit();}catch{signal('SIGKILL');await waitForExit();}}release();}if(cleanupFailed)fail('native_cleanup_unknown');})();const pending=closing;void pending.catch(()=>{if(closing===pending)closing=undefined;});return pending;};
 try{const version=await exec(binary,['--version'],{cwd,env,timeout:5000,maxBuffer:4096,killSignal:'SIGKILL'});if(version.stdout.trim()!=='codex-cli 0.146.0')fail('native_version_unsupported');
  child=spawn(binary,['app-server','--listen','stdio://'],{cwd,env,detached:true,stdio:['pipe','pipe','pipe']});exited=new Promise<void>(resolve=>{child!.once('close',()=>{retire();resolve();void close().catch(()=>{});});});child.once('exit',()=>{retire();void close().catch(()=>{});});child.on('error',()=>rpc?.close());child.stderr.resume();rpc=new CodexRpc(child.stdout,child.stdin,{timeoutMs:options.timeoutMs});await rpc.call('initialize',{clientInfo:{name:'durebak_owned',version:'0.1.0-alpha.12'},capabilities:{experimentalApi:true}});rpc.notify('initialized',{});const loaded=z.object({data:z.array(z.string())}).parse(await rpc.call('thread/loaded/list',{}));if(loaded.data.length)fail('native_host_not_fresh');verifyConfig(await rpc.call('config/read',{includeLayers:false}),cwd);
  const started=z.object({thread:z.object({id:short,cliVersion:z.literal('0.146.0'),cwd:z.string(),modelProvider:z.literal('openai'),ephemeral:z.literal(false),status:z.object({type:z.literal('idle')})}),cwd:z.string(),modelProvider:z.literal('openai'),approvalPolicy:z.literal('never'),activePermissionProfile:z.object({id:z.literal(permissionProfile)}),instructionSources:z.array(z.unknown())}).parse(await rpc.call('thread/start',{cwd,permissions:permissionProfile,approvalPolicy:'never',ephemeral:false}));if(realpathSync.native(started.cwd)!==cwd||realpathSync.native(started.thread.cwd)!==cwd||started.instructionSources.length)fail('native_thread_scope_conflict');fence.recordNative(started.thread.id);const mcp=z.object({data:z.array(z.unknown()),nextCursor:z.null()}).parse(await rpc.call('mcpServerStatus/list',{limit:100}));if(mcp.data.length)fail('native_mcp_scope_conflict');await verifyCommands(rpc,profile,cwd);if(closed)fail('native_host_closed');const metadata=Object.freeze({profile,nativeId:started.thread.id,epoch:1,instance:options.instance,cli_version:'0.146.0',command_scope_verified:true,model_verified:false,auto_wake:false});const ownedRpc=rpc;
  return Object.freeze({metadata,attach(id:string){short.parse(id);if(closed)fail('native_host_closed');if(bindingId&&id!==bindingId)fail('native_binding_conflict');if(!turns){turns=new CodexTurns(fence,ownedRpc,{binding:{bindingId:id,profile,nativeId:metadata.nativeId,epoch:1,instance:options.instance},cwd,permissionProfile});bindingId=id;}return turns;},close});
 }catch{try{await close();}catch{fail('native_shutdown_unknown');}fail('native_host_bootstrap_failed');}
}
