import type {DatabaseSync} from 'node:sqlite';
import {z} from 'zod';
import {fail,hash,type Session} from './domain.js';
import {managedPolicyDigest,type ManagedPolicy} from './managed-control.js';
import {RequestRepository,requestCreateSchema} from './requests.js';
import {ScopedAttachments} from './scoped-attachments.js';
import {ProtectedTasks} from './protected-tasks.js';
import {RequestPreviewRepository} from './request-preview.js';
import {messageQueue} from './message-queue.js';
export interface ExecutionOrigin {binding:{id:string;session_id:string;workspace:string;epoch:number;instance:string};attempt:{id:string;request_id:string;state:string;driver_outcome:string|null;input_accepted:number;stop_requested:number;source:string;policy_digest:string;root_policy_digest:string}}
export class Continuations {
 constructor(private db:DatabaseSync,private clock:{now():number}){}
 private policy(id:string){const p=this.db.prepare('SELECT * FROM managed_policies WHERE binding_id=?').get(id) as unknown as ManagedPolicy|undefined;if(!p||!p.enabled||p.expired||p.expires_at===null||p.expires_at<=this.clock.now())fail('policy_off');return p;}
 private repository(){const attachments=new ScopedAttachments(this.db),preview=new RequestPreviewRepository(this.db,this.clock,attachments);return new RequestRepository(this.db,this.clock,(actor,input,now)=>messageQueue(this.db).enqueue(actor,input,now),(actor,id,input,now)=>{preview.validate(actor,id,input,now);},new ProtectedTasks(this.db),attachments);}
 create(origin:ExecutionOrigin,input:z.input<typeof requestCreateSchema>){if(!this.db.isTransaction)fail('transaction_required');const data=requestCreateSchema.parse(input),digest=hash(JSON.stringify(data)),{binding:b,attempt:a}=origin,actor=this.db.prepare('SELECT id,workspace,alias,provider,revoked FROM sessions WHERE id=?').get(b.session_id) as unknown as Session,repository=this.repository();
  const old=this.db.prepare('SELECT id FROM requests WHERE creator=? AND key=?').get(actor.id,data.key) as {id:string}|undefined;if(old){const child=this.db.prepare('SELECT parent_attempt,intent_digest FROM work_children WHERE request_id=?').get(old.id) as {parent_attempt:string;intent_digest:string}|undefined;if(!child||child.parent_attempt!==a.id)fail('execution_origin_conflict');if(child.intent_digest!==digest)fail('idempotency_conflict');return repository.get(actor,old.id);}
  if(a.state!=='submitting'||a.driver_outcome!=='running'||!a.input_accepted||a.stop_requested||actor.revoked)fail('execution_not_running');
  const owner=this.db.prepare('SELECT execution_state FROM native_bindings WHERE id=?').get(b.id)!;if(owner.execution_state==='unknown')fail('execution_unknown');
  const q=this.db.prepare('SELECT state,deadline_at FROM requests WHERE id=?').get(a.request_id) as {state:string;deadline_at:number};const incoming=JSON.parse(a.source) as {trigger:{kind:string}};const resumed=!!this.db.prepare("SELECT request_id FROM work_waiters WHERE claim_attempt=? AND status='claimed'").get(a.id);if(q.state!=='accepted'&&!(q.state==='completed'&&resumed&&incoming.trigger.kind==='result'))fail('parent_request_not_accepted');
  const parent=this.db.prepare('SELECT * FROM work_scopes WHERE request_id=?').get(a.request_id) as {root_request_id:string;owner_binding:string;scope_id:string;max_turns:number;max_concurrent:number;expires_at:number},rootId=parent.root_request_id??a.request_id,rootScope=this.db.prepare('SELECT * FROM work_scopes WHERE request_id=?').get(rootId) as typeof parent;
  const policy=this.policy(b.id),root=this.policy(rootScope.owner_binding);if(a.policy_digest!==managedPolicyDigest(policy)||a.root_policy_digest!==managedPolicyDigest(root))fail('policy_changed');if(!JSON.parse(policy.allowed_peers).includes(data.to)||(data.to!==(this.db.prepare('SELECT session_id FROM native_bindings WHERE id=?').get(rootScope.owner_binding)!.session_id)&&!JSON.parse(root.allowed_peers).includes(data.to)))fail('peer_not_allowed');
  const rootRequest=this.db.prepare('SELECT state,deadline_at FROM requests WHERE id=?').get(rootId) as {state:string;deadline_at:number};if(!['pending','accepted'].includes(rootRequest.state))fail('root_request_closed');
  const now=this.clock.now(),deadline=Math.min(now+data.deadlineMs,q.deadline_at,rootRequest.deadline_at,parent.expires_at,policy.expires_at!,root.expires_at!);if(deadline<=now)fail('request_closed');
  const child=repository.createWithinTransaction(actor,{...data,deadlineMs:deadline-now});this.db.prepare('INSERT INTO work_children(request_id,parent_attempt,root_request_id,intent_digest) VALUES(?,?,?,?)').run(child.id,a.id,rootId,digest);
  this.db.prepare('INSERT INTO work_scopes(request_id,scope_id,owner_binding,max_turns,max_concurrent,expires_at,root_request_id) VALUES(?,?,?,?,?,?,?)').run(child.id,rootScope.scope_id,rootScope.owner_binding,rootScope.max_turns,rootScope.max_concurrent,deadline,rootId);return child;
 }
 wait(origin:ExecutionOrigin,requestId:string){if(!this.db.isTransaction)fail('transaction_required');const {binding:b,attempt:a}=origin,child=this.db.prepare('SELECT r.creator,r.state,r.deadline_at,c.parent_attempt,s.owner_binding FROM requests r JOIN work_children c ON c.request_id=r.id JOIN work_scopes s ON s.request_id=r.id WHERE r.id=?').get(requestId) as {creator:string;state:string;deadline_at:number;parent_attempt:string;owner_binding:string}|undefined;if(!child||child.creator!==b.session_id||child.parent_attempt!==a.id)fail('waiting_origin_mismatch');const p=this.policy(b.id),root=this.policy(child.owner_binding);if(a.policy_digest!==managedPolicyDigest(p)||a.root_policy_digest!==managedPolicyDigest(root))fail('policy_changed');const ancestor=this.db.prepare('SELECT r.state,r.deadline_at FROM requests r JOIN work_children c ON c.root_request_id=r.id WHERE c.request_id=?').get(requestId) as {state:string;deadline_at:number};if(!['pending','accepted'].includes(ancestor.state)||ancestor.deadline_at<=this.clock.now())fail('root_request_closed');if(child.deadline_at<=this.clock.now()||!['pending','accepted','completed'].includes(child.state)||a.stop_requested)fail('request_closed');
  this.db.prepare("INSERT INTO work_waiters(request_id,origin_attempt,binding_id,epoch,instance,policy_digest,root_policy_digest,deadline_at,status) VALUES(?,?,?,?,?,?,?,?,'waiting')").run(requestId,a.id,b.id,b.epoch,b.instance,managedPolicyDigest(p),managedPolicyDigest(root),Math.min(child.deadline_at,p.expires_at!,root.expires_at!));
 }
}

// Observation latches closure independently of the following rejected operation.
export function expireWaiters(db:DatabaseSync,now:number){db.prepare("UPDATE work_waiters SET status='expired' WHERE status IN ('waiting','claimed') AND deadline_at<=?").run(now);db.exec("UPDATE work_waiters SET status='cancelled' WHERE status IN ('waiting','claimed') AND (binding_id IN (SELECT binding_id FROM managed_policies WHERE enabled=0 OR expired=1) OR request_id IN (SELECT s.request_id FROM work_scopes s JOIN requests r ON r.id=s.root_request_id JOIN managed_policies p ON p.binding_id=s.owner_binding WHERE r.state NOT IN ('pending','accepted') OR p.enabled=0 OR p.expired=1) OR request_id IN (SELECT id FROM requests WHERE state IN ('cancelled','timed_out','rejected','failed')))");}
export function childPermission(db:DatabaseSync,requestId:string,now:number):string|null {
 const child=db.prepare('SELECT r.recipient,a.binding_id,c.root_request_id FROM work_children c JOIN requests r ON r.id=c.request_id JOIN work_attempts a ON a.id=c.parent_attempt WHERE c.request_id=?').get(requestId) as {recipient:string;binding_id:string;root_request_id:string}|undefined;if(!child)return null;
 const ancestors=db.prepare(`WITH RECURSIVE lineage(id) AS (SELECT a.request_id FROM work_children c JOIN work_attempts a ON a.id=c.parent_attempt WHERE c.request_id=? UNION SELECT a.request_id FROM lineage l JOIN work_children c ON c.request_id=l.id JOIN work_attempts a ON a.id=c.parent_attempt) SELECT r.state,r.deadline_at FROM lineage l JOIN requests r ON r.id=l.id`).all(requestId) as {state:string;deadline_at:number}[];for(const ancestor of ancestors){if(ancestor.deadline_at<=now)return 'request_deadline';if(['cancelled','timed_out','rejected','failed'].includes(ancestor.state))return 'ancestor_request_closed';}
 const root=db.prepare('SELECT owner_binding FROM work_scopes WHERE request_id=?').get(child.root_request_id) as {owner_binding:string};
 for(const id of new Set([child.binding_id,root.owner_binding])){const grant=db.prepare('SELECT p.enabled,p.expired,p.expires_at,p.allowed_peers,b.session_id,s.revoked,s.availability FROM managed_policies p JOIN native_bindings b ON b.id=p.binding_id JOIN sessions s ON s.id=b.session_id WHERE p.binding_id=?').get(id) as {enabled:number;expired:number;expires_at:number|null;allowed_peers:string;session_id:string;revoked:number;availability:string};if(grant.revoked)return 'binding_revoked';if(grant.availability==='paused')return 'recipient_paused';if(!grant.enabled)return 'root_policy_off';if(grant.expired||grant.expires_at===null||grant.expires_at<=now)return 'grant_expired';if(grant.session_id!==child.recipient&&!JSON.parse(grant.allowed_peers).includes(child.recipient))return 'peer_not_allowed';}
 return null;
}
