import type {DatabaseSync,SQLInputValue} from 'node:sqlite';
import {timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {fail,hash,short} from './domain.js';
import {transaction} from './transactions.js';
import {childPermission,expireWaiters,Continuations} from './continuations.js';
import {WorkReservations} from './work-reservations.js';
import {expireRequestsWithinTransaction} from './requests.js';
const bindingSchema=z.object({bindingId:short,epoch:z.number().int().positive(),instance:short,profile:short,nativeId:short}).strict();
type DriverBinding=z.infer<typeof bindingSchema>;
interface DriverIdentity extends DriverBinding {attemptId:string;sourceDigest:string}
const outcomeSchema=z.object({attemptId:short,epoch:z.number().int().positive(),instance:short,sourceDigest:z.string().regex(/^[a-f0-9]{64}$/),turnId:short.nullable(),accepted:z.boolean().nullable(),state:z.enum(['running','succeeded','failed','waiting_user','awaiting_peer','stopped','not_accepted','unknown']) ,waitingRequestId:short.optional()}).strict().superRefine((r,c)=>{
 if((r.state==='awaiting_peer')!==!!r.waitingRequestId)c.addIssue({code:'custom',message:'invalid_waiting_receipt'});
 if((r.accepted===true&&!r.turnId)||(r.state==='not_accepted'&&(r.accepted!==false||r.turnId!==null))||(!['unknown','not_accepted'].includes(r.state)&&r.accepted!==true))c.addIssue({code:'custom',message:'invalid_driver_outcome'});
});
type Outcome=z.infer<typeof outcomeSchema>;
const authority=new WeakSet<object>();
// Only this factory creates the trusted mock implementation. Peer-supplied
// read-only flags and structural driver objects cannot enable execution.
export function createMockDriver(input:DriverBinding){
 const binding=Object.freeze(bindingSchema.parse(input)),turns=new Map<string,Outcome>();let readiness:'ready'|'busy'|'unknown'='ready',submitMode:'accept'|'reject'|'lose-response'='accept',interruptMode:'stopped'|'unknown'='stopped';const calls={submit:0,observe:0,interrupt:0};
 const check=(id:DriverIdentity)=>{for(const key of ['bindingId','epoch','instance','profile','nativeId'] as const)if(id[key]!==binding[key])fail('driver_identity_mismatch');};
 const unknown=(id:DriverIdentity):Outcome=>({attemptId:id.attemptId,epoch:id.epoch,instance:id.instance,sourceDigest:id.sourceDigest,turnId:null,accepted:null,state:'unknown'});
 const driver=Object.freeze({kind:'read-only-mock' as const,binding,calls,
  probe:()=>readiness==='ready'&&[...turns.values()].some(r=>['running','waiting_user','unknown'].includes(r.state))?'busy':readiness,
  async submit(id:DriverIdentity,source:string):Promise<Outcome>{check(id);if(hash(source)!==id.sourceDigest)fail('source_changed');if(turns.has(id.attemptId))fail('duplicate_submission');calls.submit++;const result:Outcome={...unknown(id),turnId:submitMode==='reject'?null:`mock-turn:${id.attemptId}`,accepted:submitMode!=='reject',state:submitMode==='reject'?'not_accepted':'running'};turns.set(id.attemptId,result);if(submitMode==='lose-response')throw new Error('mock_response_lost');return {...result};},
  async observe(id:DriverIdentity):Promise<Outcome>{check(id);calls.observe++;return {...(turns.get(id.attemptId)??unknown(id))};},
  async interrupt(id:DriverIdentity):Promise<Outcome>{check(id);calls.interrupt++;const old=turns.get(id.attemptId);if(!old||interruptMode==='unknown')return unknown(id);if(old.accepted===true){const {waitingRequestId,...base}=old;const stopped={...base,state:'stopped' as const};turns.set(id.attemptId,stopped);return {...stopped};}return {...old};},
  setAwaiting(id:string,requestId:string){const old=turns.get(id);if(!old||old.accepted!==true)fail('not_found');turns.set(id,{...old,state:'awaiting_peer',waitingRequestId:requestId});},
  setOutcome(id:string,state:'succeeded'|'failed'|'waiting_user'|'stopped'|'unknown'){const old=turns.get(id);if(!old)fail('not_found');const {waitingRequestId,...base}=old;turns.set(id,{...base,state});},
  setReadiness(value:'ready'|'busy'|'unknown'){readiness=value;},setSubmitMode(value:typeof submitMode){submitMode=value;},setInterruptMode(value:typeof interruptMode){interruptMode=value;}
 });authority.add(driver);return driver;
}
type MockDriver=ReturnType<typeof createMockDriver>;
const operationSchema=z.object({bindingId:short,epoch:z.number().int().positive(),instance:short,ownerToken:z.string().regex(/^[a-f0-9]{64}$/),messageId:short,key:short,driver:z.string()}).strict();
const executionSchema=operationSchema.extend({attemptId:short}).strict();
type Operation=z.input<typeof operationSchema>;type Execution=z.input<typeof executionSchema>;
interface Binding {id:string;session_id:string;workspace:string;epoch:number;instance:string;owner_hash:string;profile:string;native_id:string}
interface Attempt {id:string;binding_id:string;workspace:string;request_id:string;message_id:string;epoch:number;instance:string;key:string;source_digest:string;source:string;state:string;driver_outcome:string|null;driver_turn_id:string|null;input_accepted:number;stop_requested:number;stop_reason:string|null;outcome_observed_ms:number|null;active_released:number;budget_returned:number;charged_bindings:string;policy_digest:string;root_policy_digest:string}
export class ExecutionController {
 constructor(private db:DatabaseSync,private clock:{now():number},private driver:MockDriver){}
 createChild(input:Execution,payload:Parameters<Continuations['create']>[1]){const data=executionSchema.parse(input);this.observeTime(data);return transaction(this.db,()=>new Continuations(this.db,this.clock).create((()=>{const {b,a}=this.attempt(data);const reason=this.blocked(b,a);if(reason)fail(reason);return {binding:b,attempt:a};})(),payload));}
 private one<T>(sql:string,...args:SQLInputValue[]){return this.db.prepare(sql).get(...args) as T|undefined;}
 private authorize(data:Operation){if(!authority.has(this.driver)||data.driver!=='read-only-mock')fail('driver_unverified');const b=this.one<Binding>('SELECT * FROM native_bindings WHERE id=?',data.bindingId);if(!b)fail('not_found');const actual=Buffer.from(hash(data.ownerToken)),expected=Buffer.from(b.owner_hash);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))fail('unauthorized');if(b.epoch!==data.epoch)fail('owner_epoch_conflict');if(b.instance!==data.instance)fail('owner_instance_conflict');const id={bindingId:b.id,epoch:b.epoch,instance:b.instance,profile:b.profile,nativeId:b.native_id};for(const key of ['bindingId','epoch','instance','profile','nativeId'] as const)if(id[key]!==this.driver.binding[key])fail('driver_identity_mismatch');return b;}
 private observeTime(data:Operation){const now=this.clock.now();transaction(this.db,()=>{const b=this.authorize(data);this.db.prepare("UPDATE native_bindings SET execution_state=CASE WHEN lease_until<=? OR last_observed_ms>? THEN 'unknown' ELSE execution_state END,last_observed_ms=max(last_observed_ms,?) WHERE id=?").run(now,now,now,b.id);this.db.prepare('UPDATE managed_policies SET expired=1 WHERE binding_id=? AND expires_at IS NOT NULL AND expires_at<=?').run(b.id,now);this.db.prepare('UPDATE managed_policies SET expired=1 WHERE binding_id IN (SELECT ws.owner_binding FROM work_scopes ws JOIN work_attempts a ON a.request_id=ws.request_id WHERE a.binding_id=?) AND expires_at<=?').run(b.id,now);this.db.prepare('UPDATE managed_policies SET expired=1 WHERE expires_at IS NOT NULL AND expires_at<=?').run(now);expireRequestsWithinTransaction(this.db,now);expireWaiters(this.db,now);});}
 private attempt(data:Execution){const b=this.authorize(data),a=this.one<Attempt>('SELECT * FROM work_attempts WHERE id=? AND binding_id=?',data.attemptId,b.id);if(!a)fail('not_found');if(a.epoch!==b.epoch||a.instance!==b.instance)fail('owner_epoch_conflict');if(a.message_id!==data.messageId||a.key!==data.key)fail('idempotency_conflict');return {b,a};}
 private identity(a:Attempt):DriverIdentity{return {...this.driver.binding,attemptId:a.id,sourceDigest:a.source_digest};}
 private view(a:Attempt,reason:string|null=null){return {id:a.id,state:a.driver_outcome??a.state,input_accepted:!!a.input_accepted,attempt_stopped:a.active_released?true:a.stop_requested||a.state==='unknown'?'unknown' as const:false,reason:reason??a.stop_reason,source_digest:a.source_digest,driver_kind:'read-only-mock',native_verified:false,model_started:false};}
 private blocked(b:Binding,a:Attempt){const now=this.clock.now(),p=this.one<{enabled:number;expired:number;expires_at:number|null}>('SELECT enabled,expired,expires_at FROM managed_policies WHERE binding_id=?',b.id)!,session=this.one<{revoked:number;availability:string}>('SELECT revoked,availability FROM sessions WHERE id=?',b.session_id)!,q=this.one<{state:string;deadline_at:number}>('SELECT state,deadline_at FROM requests WHERE id=?',a.request_id)!,m=this.one<{expires_at:number|null}>('SELECT expires_at FROM messages WHERE id=?',a.message_id)!;
  const permission=childPermission(this.db,a.request_id,now);if(permission)return permission;
  const lineage=this.one<{root_request_id:string;owner_binding:string}>('SELECT s.root_request_id,r.owner_binding FROM work_scopes s JOIN work_scopes r ON r.request_id=s.root_request_id WHERE s.request_id=?',a.request_id);if(lineage&&lineage.root_request_id!==a.request_id){const root=this.one<{enabled:number;expired:number;expires_at:number|null}>('SELECT enabled,expired,expires_at FROM managed_policies WHERE binding_id=?',lineage.owner_binding)!;const request=this.one<{state:string;deadline_at:number}>('SELECT state,deadline_at FROM requests WHERE id=?',lineage.root_request_id)!;const rootSession=this.one<{revoked:number;availability:string}>('SELECT s.revoked,s.availability FROM sessions s JOIN native_bindings b ON b.session_id=s.id WHERE b.id=?',lineage.owner_binding)!;if(rootSession.revoked)return 'binding_revoked';if(rootSession.availability==='paused')return 'recipient_paused';if(!root.enabled)return 'root_policy_off';if(root.expired||root.expires_at===null||root.expires_at<=now)return 'grant_expired';if(request.deadline_at<=now)return 'request_deadline';if(!['pending','accepted'].includes(request.state))return 'root_request_closed';}
  return !p.enabled?'policy_off':session.revoked?'binding_revoked':session.availability==='paused'?'recipient_paused':p.expired||p.expires_at===null||p.expires_at<=now?'grant_expired':q.deadline_at<=now?'request_deadline':['cancelled','timed_out','rejected','failed'].includes(q.state)?'request_closed':m.expires_at!==null&&m.expires_at<=now?'trigger_expired':null;
 }
 reserve(input:Operation){const data=operationSchema.parse(input);this.observeTime(data);const previous=this.one<{id:string;intent_digest:string}>('SELECT id,intent_digest FROM work_attempts WHERE binding_id=? AND key=?',data.bindingId,data.key);if(previous){if(previous.intent_digest!==hash(JSON.stringify({...data,ownerToken:undefined})))fail('idempotency_conflict');return this.view(this.attempt({...data,attemptId:previous.id}).a);}const readiness=this.driver.probe();if(readiness!=='ready')fail(readiness==='busy'?'host_busy':'host_unknown');return new WorkReservations(this.db,this.clock).reserve(data);}
 private release(a:Attempt,refund:boolean){if(a.active_released)return;const scope=this.one<{root_request_id:string|null}>('SELECT root_request_id FROM work_scopes WHERE request_id=?',a.request_id)!;for(const bindingId of JSON.parse(a.charged_bindings) as string[]){if(this.db.prepare('UPDATE managed_policies SET active_turns=active_turns-1,spent_turns=spent_turns-? WHERE binding_id=? AND active_turns>0 AND spent_turns>=?').run(refund?1:0,bindingId,refund?1:0).changes!==1)fail('budget_corrupt');}for(const requestId of new Set([a.request_id,scope.root_request_id??a.request_id])){if(this.db.prepare('UPDATE work_scopes SET active_turns=active_turns-1,spent_turns=spent_turns-? WHERE request_id=? AND active_turns>0 AND spent_turns>=?').run(refund?1:0,requestId,refund?1:0).changes!==1)fail('budget_corrupt');}this.db.prepare('DELETE FROM work_reservations WHERE attempt_id=?').run(a.id);this.db.prepare('UPDATE work_attempts SET active_released=1,budget_returned=? WHERE id=?').run(refund?1:0,a.id);}
 private persist(data:Execution,raw:unknown){const r=outcomeSchema.parse(raw);this.observeTime(data);return transaction(this.db,()=>{
  const {b,a}=this.attempt(data);if(['completed','cancelled'].includes(a.state))return this.view(a);
  if(r.attemptId!==a.id||r.epoch!==a.epoch||r.instance!==a.instance||r.sourceDigest!==a.source_digest)fail('driver_receipt_mismatch');if(a.driver_turn_id&&r.turnId&&a.driver_turn_id!==r.turnId)fail('driver_turn_conflict');if(a.input_accepted&&r.accepted===false)fail('driver_acceptance_conflict');
  if(r.accepted===true&&!a.input_accepted){if(hash(a.source)!==a.source_digest)fail('source_changed');const source=JSON.parse(a.source) as {messages:{id:string;recipient:string;sender:string}[]};const locked=this.db.prepare('SELECT message_id FROM work_reservations WHERE attempt_id=?').all(a.id).map(row=>row.message_id as string);const expected=source.messages.filter(m=>m.recipient===b.session_id&&m.sender!==b.session_id&&this.one<{delivered_at:number|null}>('SELECT delivered_at FROM messages WHERE id=?',m.id)?.delivered_at===null).map(m=>m.id);if(JSON.stringify([...locked].sort())!==JSON.stringify(expected.sort()))fail('reservation_changed');
   for(const id of locked){this.db.prepare("UPDATE messages SET status='delivered',delivered_at=coalesce(delivered_at,?),lease_until=NULL WHERE id=? AND recipient=?").run(this.clock.now(),id,b.session_id);this.db.prepare('INSERT OR IGNORE INTO delivery_audit(message_id,recipient) VALUES(?,?)').run(id,b.session_id);this.db.prepare('INSERT INTO events(workspace,kind,entity,created_at) VALUES(?,?,?,?)').run(b.workspace,'message.managed_delivered',id,new Date(this.clock.now()).toISOString());}
  }
  if(r.state==='awaiting_peer'){if(this.blocked(b,a))fail('request_closed');new Continuations(this.db,this.clock).wait({binding:b,attempt:a},r.waitingRequestId!);}
  const terminal=['succeeded','failed','stopped','not_accepted','awaiting_peer'].includes(r.state),uncertain=r.state==='unknown'||!!a.stop_requested&&!terminal,state=terminal?'completed':uncertain?'unknown':'submitting',outcome=uncertain?'unknown':r.state;
  this.db.prepare('UPDATE work_attempts SET state=?,driver_outcome=?,driver_receipt=?,driver_turn_id=coalesce(driver_turn_id,?),input_accepted=max(input_accepted,?),outcome_observed_ms=? WHERE id=?').run(state,outcome,JSON.stringify(r),r.turnId,r.accepted===true?1:0,Math.max(a.outcome_observed_ms??0,this.clock.now()),a.id);if(terminal)this.release(a,r.state==='not_accepted');return this.view(this.one<Attempt>('SELECT * FROM work_attempts WHERE id=?',a.id)!);
 });}
 private uncertain(data:Execution,reason:string){try{this.observeTime(data);return transaction(this.db,()=>{const {a}=this.attempt(data);if(['completed','cancelled'].includes(a.state))return this.view(a);this.db.prepare("UPDATE work_attempts SET state='unknown',driver_outcome='unknown' WHERE id=?").run(a.id);return this.view(this.one<Attempt>('SELECT * FROM work_attempts WHERE id=?',a.id)!,reason);});}catch{return {...this.view(this.attempt(data).a,reason),state:'unknown'};}}
 async execute(input:Execution){const data=executionSchema.parse(input);this.observeTime(data);const {a}=this.attempt(data);if(a.state!=='reserved')fail('submission_uncertain');const readiness=this.driver.probe();if(readiness!=='ready')fail(readiness==='busy'?'host_busy':'host_unknown');new WorkReservations(this.db,this.clock).submitting(data);
  let response:Outcome;try{response=await this.driver.submit(this.identity(a),a.source);}catch{return this.uncertain(data,'submission_response_lost');}
  try{const view=this.persist(data,response);return this.blocked(this.attempt(data).b,this.attempt(data).a)&&!['completed','cancelled'].includes(this.attempt(data).a.state)?await this.reconcile(data):view;}catch{return this.uncertain(data,'outcome_not_recorded');}
 }
 async reconcile(input:Execution){const data=executionSchema.parse(input);this.observeTime(data);const {b,a}=this.attempt(data);if(['completed','cancelled'].includes(a.state))return this.view(a);const reason=this.blocked(b,a);
  if(a.state==='reserved'){if(!reason)return this.view(a);return transaction(this.db,()=>{const current=this.attempt(data).a;if(current.state!=='reserved')fail('submission_uncertain');this.db.prepare("UPDATE work_attempts SET state='cancelled',driver_outcome='not_submitted',stop_reason=? WHERE id=?").run(reason,current.id);this.release(current,true);return this.view(this.one<Attempt>('SELECT * FROM work_attempts WHERE id=?',current.id)!);});}
  if(reason&&!a.stop_requested){const claimed=transaction(this.db,()=>{const current=this.attempt(data).a;if(!['submitting','unknown'].includes(current.state))fail('submission_uncertain');return this.db.prepare('UPDATE work_attempts SET stop_requested=1,stop_reason=? WHERE id=? AND stop_requested=0').run(reason,current.id).changes===1;});if(!claimed)return this.view(this.attempt(data).a);try{return this.persist(data,await this.driver.interrupt(this.identity(a)));}catch{return this.uncertain(data,'interrupt_response_unknown');}}
  try{return this.persist(data,await this.driver.observe(this.identity(a)));}catch{return this.uncertain(data,'observation_unknown');}
 }
}
