import {spawn,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {lstatSync,realpathSync,readdirSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {createServer} from 'node:net';
import {randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {fail,short} from './domain.js';
import {NativePeerInspector,NativePeerBuildError} from './native-peer-inspector.js';
import {OwnedPeerConnector} from './owned-peer-connector.js';
import {NativeProfileFence} from './native-profile-fence.js';
import {nativeBootstrapCommand,compileNativeBootstrap} from './native-bootstrap-sandbox.js';
import {OpencodeHttp} from './opencode-http.js';
import {normalizeOpencodeReadiness,opencodeSessionState} from './opencode-readiness.js';
const optionsSchema=z.object({binary:z.string().min(1),runtimeRoot:z.string().min(1),profile:z.string().min(1),cwd:z.string().min(1),instance:short,providerId:short,modelId:short,timeoutMs:z.number().int().min(10).max(20000).default(20000),shutdownMs:z.number().int().min(10).max(3000).default(1000)}).strict();
export type OwnedOpencodeOptions=z.input<typeof optionsSchema>;
function privateEmpty(path:string){const normalized=resolve(path),stat=lstatSync(normalized);if(stat.isSymbolicLink()||!stat.isDirectory()||(stat.mode&0o077)!==0||stat.uid!==process.getuid?.()||realpathSync.native(normalized)!==normalized||readdirSync(normalized).length)fail('native_directory_unsafe');return normalized;}
async function freePort(){const server=createServer();return new Promise<number>((accept,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const port=(server.address() as {port:number}).port;server.close(error=>error?reject(error):accept(port));});});}
function verifyConfig(raw:unknown,provider:string){const c=z.object({share:z.literal('disabled'),permission:z.record(z.string(),z.unknown()),plugin:z.array(z.unknown()),mcp:z.record(z.string(),z.unknown()),autoupdate:z.literal(false),enabled_providers:z.array(z.string())}).passthrough().parse(raw);if(JSON.stringify(c.permission)!=='{"*":"deny"}'||c.plugin.length||Object.keys(c.mcp).length||c.enabled_providers.length!==1||c.enabled_providers[0]!==provider)fail('native_effective_config_conflict');for(const key of ['instructions','provider','agent','command','tools']){const value=c[key];if(value!==undefined&&(typeof value!=='object'||value===null||Object.keys(value).length))fail('native_effective_config_conflict');}}
function verifyStatuses(raw:unknown,nativeId:string){const state=opencodeSessionState(raw,nativeId);if(Object.keys(raw as object).some(id=>id!==nativeId))fail('native_session_scope_conflict');return state;}
function verifySession(raw:unknown,options:{cwd:string;providerId:string;modelId:string;nonce:string;nativeId?:string}){const s=z.object({id:z.string().regex(/^ses_[A-Za-z0-9]+$/).max(200),directory:z.literal(options.cwd),version:z.literal('1.18.34'),agent:z.literal('build'),model:z.object({id:z.literal(options.modelId),providerID:z.literal(options.providerId)}).strict(),permission:z.array(z.object({permission:z.literal('*'),pattern:z.literal('*'),action:z.literal('deny')}).strict()).length(1),metadata:z.object({durebakOwner:z.literal(options.nonce)}).strict(),time:z.object({created:z.number().finite(),updated:z.number().finite()}).passthrough()}).passthrough().parse(raw);if(options.nativeId&&s.id!==options.nativeId)fail('native_session_identity_conflict');for(const key of ['parentID','workspaceID','share','revert','summary'])if(s[key]!==undefined)fail('native_session_scope_conflict');if(s.time.archived!==undefined||s.time.compacting!==undefined)fail('native_session_scope_conflict');return s.id;}
// Fresh non-model bootstrap only. The private roots and fixed native session
// are owned; no transport, submission or controller authority is exposed.
// This macOS scope permits bootstrap input/runtime writes, not provider access.
export async function startOwnedOpencodeHost(input:OwnedOpencodeOptions){
 if(process.platform!=='darwin')fail('native_bootstrap_unsupported');const options=optionsSchema.parse(input),runtime=privateEmpty(options.runtimeRoot),cwd=privateEmpty(options.cwd),profile=privateEmpty(options.profile),port=await freePort();const scope={binary:options.binary,runtimeRoot:runtime,inputRoot:cwd,ownerProfile:profile,port};compileNativeBootstrap(scope);
 const fence=NativeProfileFence.claim(profile,options.instance);let child:ChildProcessWithoutNullStreams|undefined,http:OpencodeHttp|undefined,closed=false,released=false,closing:Promise<void>|undefined,exited:Promise<void>|undefined,nativeId:string|undefined,inspector:NativePeerInspector|undefined;
 const retire=()=>{closed=true;http?.close();};
 const signal=(name:NodeJS.Signals)=>{if(!child?.pid)return;try{process.kill(-child.pid,name);}catch(error){if(!['ESRCH','EPERM'].includes((error as NodeJS.ErrnoException).code??''))throw error;}};
 const groupGone=()=>{if(!child?.pid)return true;try{process.kill(-child.pid,0);return false;}catch(error){if((error as NodeJS.ErrnoException).code==='ESRCH')return true;if((error as NodeJS.ErrnoException).code==='EPERM')return false;throw error;}};
 const waitExit=async()=>{const deadline=Date.now()+options.shutdownMs;while(!groupGone()){if(Date.now()>=deadline)fail('native_shutdown_timeout');await new Promise(r=>setTimeout(r,10));}if(exited){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([exited,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('native_shutdown_timeout')),Math.max(1,deadline-Date.now()));})]);}finally{clearTimeout(timer);}}};
 const close=()=>{if(closing)return closing;closing=(async()=>{retire();if(!released){if(child){child.stdin.end();signal('SIGTERM');try{await waitExit();}catch{signal('SIGKILL');await waitExit();}}await inspector?.close();fence.close();released=true;}})();const pending=closing;void pending.catch(()=>{if(closing===pending)closing=undefined;});return pending;};
 const assertLive=()=>{if(closed||fence.status().state!=='owned')fail('native_host_closed');};
 const nonce=randomUUID();
 try{
  inspector=await NativePeerInspector.build();const within=(a:string,b:string)=>a===b||a.startsWith(b+'/');if([runtime,cwd,profile].some(root=>within(inspector!.root,root)||within(root,inspector!.root)))fail('native_peer_scope_conflict');
  const paths=Object.fromEntries(['config','data','cache','state','home','tmp','managed'].map(name=>{const path=join(runtime,name);mkdirSync(path,{mode:0o700});return [name,path];}));
  const config={share:'disabled',permission:{'*':'deny'},plugin:[],mcp:{},autoupdate:false,enabled_providers:[options.providerId]};
  const env:NodeJS.ProcessEnv={PATH:'/usr/bin:/bin',HOME:paths.home,OPENCODE_TEST_HOME:paths.home,XDG_CONFIG_HOME:paths.config,XDG_DATA_HOME:paths.data,XDG_CACHE_HOME:paths.cache,XDG_STATE_HOME:paths.state,TMPDIR:paths.tmp,OPENCODE_TEST_MANAGED_CONFIG_DIR:paths.managed,OPENCODE_PURE:'true',OPENCODE_CONFIG_CONTENT:JSON.stringify(config),OPENCODE_SERVER_USERNAME:'opencode',OPENCODE_SERVER_PASSWORD:randomBytes(32).toString('base64url')};
  for(const key of ['OPENCODE_DISABLE_AUTOUPDATE','OPENCODE_DISABLE_DEFAULT_PLUGINS','OPENCODE_DISABLE_CLAUDE_CODE','OPENCODE_DISABLE_LSP_DOWNLOAD','OPENCODE_DISABLE_MODELS_FETCH','OPENCODE_DISABLE_PROJECT_CONFIG'])env[key]='true';
  const descriptor=nativeBootstrapCommand(scope),deadline=Date.now()+options.timeoutMs;assertLive();child=spawn(descriptor.command,[...descriptor.args,'serve','--hostname','127.0.0.1','--port',String(port),'--mdns=false'],{cwd:descriptor.cwd,env,detached:true,stdio:['pipe','pipe','pipe']});
  let failedStartup:(reason:Error)=>void=()=>{};exited=new Promise<void>(resolve=>{child!.once('close',()=>{retire();resolve();failedStartup(new Error('native_host_closed'));void close().catch(()=>{});});});child.once('exit',()=>{retire();failedStartup(new Error('native_host_closed'));void close().catch(()=>{});});child.on('error',()=>{retire();failedStartup(new Error('native_host_closed'));});
  await new Promise<void>((accept,reject)=>{let bytes=0,buffer='',done=false;const timer=setTimeout(()=>finish(new Error('native_startup_timeout')),Math.max(1,deadline-Date.now()));const finish=(error?:Error)=>{if(done)return;done=true;clearTimeout(timer);failedStartup=()=>{};if(error)reject(error);else accept();};failedStartup=error=>finish(error);const output=(chunk:Buffer,stdout:boolean)=>{bytes+=chunk.length;if(bytes>65536){retire();finish(new Error('native_startup_output_limit'));void close().catch(()=>{});return;}if(!stdout||done)return;buffer+=chunk.toString('utf8');let newline;while((newline=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,newline).replace(/\r$/,'');buffer=buffer.slice(newline+1);if(line.startsWith('opencode server listening on ')){if(line!==`opencode server listening on http://127.0.0.1:${port}`)finish(new Error('native_listener_conflict'));else finish();return;}}};child!.stdout.on('data',chunk=>output(chunk,true));child!.stderr.on('data',chunk=>output(chunk,false));});
  assertLive();let birthTimer:ReturnType<typeof setTimeout>|undefined;const birth=await (async()=>{try{return await Promise.race([inspector!.observeOwnedBirth(child!.pid!),new Promise<never>((_,reject)=>{birthTimer=setTimeout(()=>reject(new Error('native_startup_timeout')),Math.max(1,deadline-Date.now()));})]);}finally{clearTimeout(birthTimer);}})();assertLive();const connector=new OwnedPeerConnector({port,timeoutMs:Math.min(2000,options.timeoutMs),assertLive,verify:async tuple=>{assertLive();await inspector!.waitOwnedPeer({birth,...tuple},assertLive,Math.min(2000,options.timeoutMs));assertLive();}});http=new OpencodeHttp({url:`http://127.0.0.1:${port}`,password:env.OPENCODE_SERVER_PASSWORD!,cwd,timeoutMs:options.timeoutMs,maxResponseBytes:2097152},connector);delete env.OPENCODE_SERVER_PASSWORD;
  const read=async(operation:Parameters<OpencodeHttp['call']>[0],data?:unknown)=>{assertLive();if(Date.now()>=deadline)fail('native_startup_timeout');let timer:ReturnType<typeof setTimeout>|undefined;let result:unknown;try{result=await Promise.race([http!.call(operation,data),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('native_startup_timeout')),Math.max(1,deadline-Date.now()));})]);}finally{clearTimeout(timer);}assertLive();if(Date.now()>=deadline)fail('native_startup_timeout');return result;};
  z.object({healthy:z.literal(true),version:z.literal('1.18.34')}).parse(await read('health'));verifyConfig(await read('config'),options.providerId);if(z.array(z.unknown()).parse(await read('sessions')).length)fail('native_host_not_fresh');if(Object.keys(z.record(z.string(),z.unknown()).parse(await read('statuses'))).length)fail('native_host_not_fresh');
  const check={cwd,providerId:options.providerId,modelId:options.modelId,nonce};nativeId=verifySession(await read('createOwnedSession',{title:'Durebak owned bootstrap',providerId:options.providerId,modelId:options.modelId,ownerNonce:nonce}),check);verifySession(await read('session',{nativeId}),{...check,nativeId:nativeId!});const sessions=z.array(z.unknown()).length(1).parse(await read('sessions'));verifySession(sessions[0],{...check,nativeId:nativeId!});if(z.array(z.unknown()).parse(await read('messages',{nativeId})).length)fail('native_host_not_fresh');if(verifyStatuses(await read('statuses'),nativeId)!=='idle')fail('native_host_not_idle');if(Object.keys(z.record(z.string(),z.unknown()).parse(await read('mcp'))).length)fail('native_mcp_scope_conflict');assertLive();fence.recordNative(nativeId);
  const metadata=Object.freeze({profile,nativeId,epoch:1,instance:options.instance,cli_version:'1.18.34',bootstrap_scope_verified:true,connected_peer_verified:true,model_tool_scope_verified:false,model_verified:false,auto_wake:false});
  return Object.freeze({metadata,async health(){assertLive();try{z.object({healthy:z.literal(true),version:z.literal('1.18.34')}).parse(await http!.call('health'));assertLive();verifyConfig(await http!.call('config'),options.providerId);assertLive();verifySession(await http!.call('session',{nativeId}),{...check,nativeId:nativeId!});assertLive();const sessions=z.array(z.unknown()).length(1).parse(await http!.call('sessions'));assertLive();verifySession(sessions[0],{...check,nativeId:nativeId!});if(z.array(z.unknown()).parse(await http!.call('messages',{nativeId})).length)fail('native_host_not_fresh');assertLive();if(Object.keys(z.record(z.string(),z.unknown()).parse(await http!.call('mcp'))).length)fail('native_mcp_scope_conflict');assertLive();const providers=await http!.call('providers');assertLive();const statuses=await http!.call('statuses');assertLive();verifyStatuses(statuses,nativeId!);return {contact:'ready' as const,...normalizeOpencodeReadiness(statuses,providers,{nativeId:nativeId!,providerId:options.providerId,modelId:options.modelId})};}catch{try{await close();}catch{fail('native_shutdown_unknown');}fail('native_health_invalid');}},close});
 }catch(error){if(error instanceof NativePeerBuildError)inspector=error.inspector;try{await close();}catch{throw new OwnedOpencodeCleanupError(close);}fail('native_host_bootstrap_failed');}
}

export class OwnedOpencodeCleanupError extends Error {constructor(readonly close:()=>Promise<void>){super('native_shutdown_unknown');}}
